import type { RecipeRow } from "./types";

export type MixProfile = {
  brand: string;
  flavor: string;
  recipeName: string;
  recipe: RecipeRow[];
};

export const MIX_SEED: {
  brands: string[];
  brandFlavors: Record<string, string[]>;
  frontlineRecipeNames: string[];
  frontlineIngredients: string[];
  frontlineRecipePresets: Record<string, RecipeRow[]>;
  profiles: MixProfile[];
} = {
  brands: ["Basha","Bobo's","Corner Booth","Hannaford","Lowe's","Lucia's","Nob Hill","Price Chopper","SMD"],

  brandFlavors: {
    "Bobo's": ["Deluxe","Breakfast"],
    "Basha": ["11' Hawaiian","12' Supreme"],
    "Corner Booth": ["Chicken Alfredo","Giardiniera","House","Pep & Jal","Spinach","Supreme"],
    "Hannaford": ["Spinach Goat Cheese","Club","4Meat"],
    "Lowe's": ["7in Red Fajita","7in White Spin","Bacon Cheeseburger","California","Caribbean","Chicken Club","Grilled Vegetable","Red Hot","Spinach","11in White Spinach"],
    "Lucia's": ["Morning Melts Americano","Morming Melts Italiano","Morning Melts Mexicano","Craft Alfredo Spinach","Craft Bacon Cheeseburger","Craft Bratwurst","Craft Caribbean","Craft Red Hot","Craft SOB","Buffalo Chicken","Supreme","Pinsa Margherita","Pinsa Spinach"],
    "Nob Hill": ["SOB","Bacon Cheeseburger","Red Hot","Caribbean"],
    "Price Chopper": ["Club"],
    "SMD": ["Supreme"],
  },

  frontlineRecipeNames: [
    "Bobos Deluxe","Bobos Breakfast","Basha 11' Hawaiian","Basha 12' Supreme",
    "Corner Booth Chicken Alfredo","Corner Booth Giardiniera","Corner Booth House",
    "Corner Booth Pep & Jal","Corner Booth Spinach","Corner Booth Supreme",
    "Hannaford Spinach Goat Cheese","Hannaford Club","Hannaford 4Meat",
    "Lowes 7in Red Fajita","Lowes 7in White Spin","Lowes Bacon Cheeseburger",
    "Lowes California","Lowes Caribbean","Lowes Chicken Club","Lowes Grilled Vegetable",
    "Lowes Red Hot","Lowes Spinach","Lowes 11in White Spinach",
    "Lucias Morning Melts Americano","Lucias Morming Melts Italiano","Lucias Morning Melts Mexicano",
    "Lucias Craft Alfredo Spinach","Lucias Craft Bacon Cheeseburger","Lucias Craft Bratwurst",
    "Lucias Craft Caribbean","Lucias Craft Red Hot","Lucias Craft SOB",
    "Lucias Buffalo Chicken","Lucias Supreme","Lucias Pinsa Margherita","Lucias Pinsa Spinach",
    "Nob Hill SOB","Nob Hill Bacon Cheeseburger","Nob Hill Red Hot","Nob Hill Caribbean",
    "Price Chopper Club","SMD Supreme",
  ],

  frontlineIngredients: [
    "Bacon","Bacon - NATURAL / tri meats tm3514u or / c&f 061anub40",
    "Bacon / (Tri Meats tm3514u or c&fb 061anub40)","Bacon / Tri Meats tm3514u or / c&f 001anub40",
    "Bacon / Tri Meats tm3514u or / c&f 061anub40",
    "Bacon, NATURAL / Tri Meats tm3514u or / c&f 061anub40",
    "Bacon, NATURAL / tri meats tm3514u or / c&f 061anub40",
    "Basil, Frozen","Black Beans, IQF","Black Olives","Buffalo Sauce, Legacy",
    "Chicken, Diced / House of Raeford 28501 or / c&f 001mpdc40",
    "Chicken, Diced / c&f - 001mpdc40 or / House of Raeford - 28501",
    "Cilantro","Corn, FR",
    "Diced Chicken / (C&F 0001mpdc40 or House of Raeford 28501)",
    "Diced Chicken / c&f 001mpdc40 or / House of Raeford 28501",
    "Diced Ham / patuxent-736543078","Diced Tomatoes","Egg",
    "FR Garlic","FR Green Peppers Strip","FR Red Onion Strip","FR Red Onion Strips",
    "FR Red Pepper Strips","FR Squash","FR Tomatoes Diced","FR Zucchini",
    "Fresh Spinach (broken up)","Garlic Powder","Garlic sauce","Garlic, Granulated",
    "Goat Cheese","Green Onion","Green Pepper Diced, Blanched","Green Pepper Strips",
    "Green Pepper Strips, Blanched","Green Peppers, FR Strips","Hot Giardiniera Mix",
    "Hot Sauce, Old Vienna","Jalapenos","Mushrooms",
    "Natural Hamburger / burke 40029","Natural Italian Sausage / c&f 140mrp240",
    "Pineapple - Drained","Red Onion","Red Onion Diced, Blanched","Red Onion Strip",
    "Red Onion Strips, FR","Red Onion, FR Strips","Red Onions Diced",
    "Red Pepper Diced, Blanched","Red Pepper Strips","Red Pepper Strips, Blanched",
    "Red Peppers, FR Strips","Salt","Sauerkraut **Drained**",
    "Scrambled Egg / Greand Prairie","Sea Salt","Spinach","Thyme, IQF",
    "Tomatoes","Tomatoes, Diced","Unsalted Butter","White Onion Strips, Blanched",
    "Yellow Onion, FR Strips","Yellow Pepper Diced, Blanched","Yellow Pepper Strips",
    "Yellow Pepper Strips, Blanched",
  ],

  frontlineRecipePresets: {
    "Bobos Deluxe": [{"ingredient":"Red Onion, FR Strips","lbs":0.4},{"ingredient":"Red Peppers, FR Strips","lbs":0.82},{"ingredient":"Green Peppers, FR Strips","lbs":0.82},{"ingredient":"Basil, Frozen","lbs":0.06},{"ingredient":"Bacon","lbs":0.75}],
    "Bobos Breakfast": [{"ingredient":"Bacon / (Tri Meats tm3514u or c&fb 061anub40)","lbs":0.7}],
    "Basha 11' Hawaiian": [{"ingredient":"Pineapple - Drained","lbs":2}],
    "Basha 12' Supreme": [{"ingredient":"Red Onion","lbs":0.75},{"ingredient":"Green Pepper Strips","lbs":0.75},{"ingredient":"Red Pepper Strips","lbs":0.75},{"ingredient":"Yellow Pepper Strips","lbs":0.75}],
    "Corner Booth Chicken Alfredo": [{"ingredient":"Diced Chicken / (C&F 0001mpdc40 or House of Raeford 28501)","lbs":2.98},{"ingredient":"Garlic Powder","lbs":0.02}],
    "Corner Booth Giardiniera": [{"ingredient":"Hot Giardiniera Mix","lbs":1.75}],
    "Corner Booth House": [{"ingredient":"White Onion Strips, Blanched","lbs":0.7},{"ingredient":"Green Pepper Strips, Blanched","lbs":1},{"ingredient":"Mushrooms","lbs":1}],
    "Corner Booth Pep & Jal": [{"ingredient":"Garlic sauce","lbs":4}],
    "Corner Booth Spinach": [{"ingredient":"Fresh Spinach (broken up)","lbs":1.75}],
    "Corner Booth Supreme": [{"ingredient":"White Onion Strips, Blanched","lbs":0.563},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.563},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.563},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.563}],
    "Hannaford Spinach Goat Cheese": [{"ingredient":"Fresh Spinach (broken up)","lbs":0.6}],
    "Hannaford Club": [{"ingredient":"Bacon, NATURAL / Tri Meats tm3514u or / c&f 061anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}],
    "Hannaford 4Meat": [{"ingredient":"Natural Italian Sausage / c&f 140mrp240","lbs":1.5},{"ingredient":"Natural Hamburger / burke 40029","lbs":0.5}],
    "Lowes 7in Red Fajita": [{"ingredient":"Red Onion Diced, Blanched","lbs":0.125},{"ingredient":"Green Pepper Diced, Blanched","lbs":0.125},{"ingredient":"Red Pepper Diced, Blanched","lbs":0.125},{"ingredient":"Yellow Pepper Diced, Blanched","lbs":0.125}],
    "Lowes 7in White Spin": [{"ingredient":"Fresh Spinach (broken up)","lbs":0.8}],
    "Lowes Bacon Cheeseburger": [{"ingredient":"Tomatoes","lbs":0.8},{"ingredient":"Bacon - NATURAL / tri meats tm3514u or / c&f 061anub40","lbs":0.5}],
    "Lowes California": [{"ingredient":"FR Tomatoes Diced","lbs":2.15},{"ingredient":"FR Red Pepper Strips","lbs":1.25},{"ingredient":"FR Red Onion Strips","lbs":0.6}],
    "Lowes Caribbean": [{"ingredient":"Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2}],
    "Lowes Chicken Club": [{"ingredient":"Tomatoes, Diced","lbs":1.25},{"ingredient":"Bacon, NATURAL / tri meats tm3514u or / c&f 061anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.2}],
    "Lowes Grilled Vegetable": [{"ingredient":"FR Tomatoes Diced","lbs":2.02},{"ingredient":"FR Squash","lbs":0.71},{"ingredient":"FR Zucchini","lbs":0.71},{"ingredient":"Red Onions Diced","lbs":0.4},{"ingredient":"FR Garlic","lbs":0.1},{"ingredient":"Sea Salt","lbs":0.03},{"ingredient":"Thyme, IQF","lbs":0.03}],
    "Lowes Red Hot": [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / House of Raeford 28501 or / c&f 001mpdc40","lbs":2.43}],
    "Lowes Spinach": [{"ingredient":"Spinach","lbs":2.3},{"ingredient":"Unsalted Butter","lbs":0.24},{"ingredient":"Salt","lbs":0.06},{"ingredient":"Egg","lbs":0.3},{"ingredient":"Garlic, Granulated","lbs":0.1}],
    "Lowes 11in White Spinach": [{"ingredient":"Fresh Spinach (broken up)","lbs":2}],
    "Lucias Morning Melts Americano": [{"ingredient":"Diced Ham / patuxent-736543078","lbs":0.4},{"ingredient":"Scrambled Egg / Greand Prairie","lbs":0.6}],
    "Lucias Morming Melts Italiano": [{"ingredient":"Fresh Spinach (broken up)","lbs":2}],
    "Lucias Morning Melts Mexicano": [{"ingredient":"Scrambled Egg / Greand Prairie","lbs":0.6}],
    "Lucias Craft Alfredo Spinach": [{"ingredient":"Fresh Spinach (broken up)","lbs":0.98}],
    "Lucias Craft Bacon Cheeseburger": [{"ingredient":"Diced Tomatoes","lbs":1.25},{"ingredient":"Bacon / Tri Meats tm3514u or / c&f 001anub40","lbs":0.5}],
    "Lucias Craft Bratwurst": [{"ingredient":"Sauerkraut **Drained**","lbs":1.3},{"ingredient":"Yellow Onion, FR Strips","lbs":0.75}],
    "Lucias Craft Caribbean": [{"ingredient":"Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2}],
    "Lucias Craft Red Hot": [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / c&f - 001mpdc40 or / House of Raeford - 28501","lbs":2.43}],
    "Lucias Craft SOB": [{"ingredient":"Black Beans, IQF","lbs":0.74},{"ingredient":"Tomatoes, Diced","lbs":0.71},{"ingredient":"Red Onion, FR Strips","lbs":0.71},{"ingredient":"Corn, FR","lbs":0.63},{"ingredient":"Yellow Pepper Strips","lbs":0.46},{"ingredient":"Cilantro","lbs":0.11}],
    "Lucias Buffalo Chicken": [{"ingredient":"Diced Chicken / c&f 001mpdc40 or / House of Raeford 28501","lbs":2.4},{"ingredient":"Buffalo Sauce, Legacy","lbs":0.1}],
    "Lucias Supreme": [{"ingredient":"Red Onion Strips, FR","lbs":0.75},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.75},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.75},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.75}],
    "Lucias Pinsa Margherita": [{"ingredient":"Goat Cheese","lbs":0.25}],
    "Lucias Pinsa Spinach": [{"ingredient":"Fresh Spinach (broken up)","lbs":1}],
    "Nob Hill SOB": [{"ingredient":"Black Beans, IQF","lbs":0.74},{"ingredient":"Tomatoes, Diced","lbs":0.71},{"ingredient":"Red Onion, FR Strips","lbs":0.71},{"ingredient":"Corn, FR","lbs":0.63},{"ingredient":"Yellow Pepper Strips","lbs":0.46},{"ingredient":"Cilantro","lbs":0.11}],
    "Nob Hill Bacon Cheeseburger": [{"ingredient":"Diced Tomatoes","lbs":1.25},{"ingredient":"Bacon / Tri Meats tm3514u or / c&f 001anub40","lbs":0.5}],
    "Nob Hill Red Hot": [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / c&f - 001mpdc40 or / House of Raeford - 28501","lbs":2.43}],
    "Nob Hill Caribbean": [{"ingredient":"FR Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2}],
    "Price Chopper Club": [{"ingredient":"Bacon / Tri Meats tm3514u or / c&f 061anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}],
    "SMD Supreme": [{"ingredient":"White Onion Strips, Blanched","lbs":0.35},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Black Olives","lbs":0.5}],
  },

  profiles: [
    { brand: "Bobo's", flavor: "Deluxe", recipeName: "Bobos Deluxe", recipe: [{"ingredient":"Red Onion, FR Strips","lbs":0.4},{"ingredient":"Red Peppers, FR Strips","lbs":0.82},{"ingredient":"Green Peppers, FR Strips","lbs":0.82},{"ingredient":"Basil, Frozen","lbs":0.06},{"ingredient":"Bacon","lbs":0.75}] },
    { brand: "Bobo's", flavor: "Breakfast", recipeName: "Bobos Breakfast", recipe: [{"ingredient":"Bacon / (Tri Meats tm3514u or c&fb 061anub40)","lbs":0.7}] },
    { brand: "Basha", flavor: "11' Hawaiian", recipeName: "Basha 11' Hawaiian", recipe: [{"ingredient":"Pineapple - Drained","lbs":2}] },
    { brand: "Basha", flavor: "12' Supreme", recipeName: "Basha 12' Supreme", recipe: [{"ingredient":"Red Onion","lbs":0.75},{"ingredient":"Green Pepper Strips","lbs":0.75},{"ingredient":"Red Pepper Strips","lbs":0.75},{"ingredient":"Yellow Pepper Strips","lbs":0.75}] },
    { brand: "Corner Booth", flavor: "Chicken Alfredo", recipeName: "Corner Booth Chicken Alfredo", recipe: [{"ingredient":"Diced Chicken / (C&F 0001mpdc40 or House of Raeford 28501)","lbs":2.98},{"ingredient":"Garlic Powder","lbs":0.02}] },
    { brand: "Corner Booth", flavor: "Giardiniera", recipeName: "Corner Booth Giardiniera", recipe: [{"ingredient":"Hot Giardiniera Mix","lbs":1.75}] },
    { brand: "Corner Booth", flavor: "House", recipeName: "Corner Booth House", recipe: [{"ingredient":"White Onion Strips, Blanched","lbs":0.7},{"ingredient":"Green Pepper Strips, Blanched","lbs":1},{"ingredient":"Mushrooms","lbs":1}] },
    { brand: "Corner Booth", flavor: "Pep & Jal", recipeName: "Corner Booth Pep & Jal", recipe: [{"ingredient":"Garlic sauce","lbs":4}] },
    { brand: "Corner Booth", flavor: "Spinach", recipeName: "Corner Booth Spinach", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":1.75}] },
    { brand: "Corner Booth", flavor: "Supreme", recipeName: "Corner Booth Supreme", recipe: [{"ingredient":"White Onion Strips, Blanched","lbs":0.563},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.563},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.563},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.563}] },
    { brand: "Hannaford", flavor: "Spinach Goat Cheese", recipeName: "Hannaford Spinach Goat Cheese", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":0.6}] },
    { brand: "Hannaford", flavor: "Club", recipeName: "Hannaford Club", recipe: [{"ingredient":"Bacon, NATURAL / Tri Meats tm3514u or / c&f 061anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}] },
    { brand: "Hannaford", flavor: "4Meat", recipeName: "Hannaford 4Meat", recipe: [{"ingredient":"Natural Italian Sausage / c&f 140mrp240","lbs":1.5},{"ingredient":"Natural Hamburger / burke 40029","lbs":0.5}] },
    { brand: "Lowe's", flavor: "7in Red Fajita", recipeName: "Lowes 7in Red Fajita", recipe: [{"ingredient":"Red Onion Diced, Blanched","lbs":0.125},{"ingredient":"Green Pepper Diced, Blanched","lbs":0.125},{"ingredient":"Red Pepper Diced, Blanched","lbs":0.125},{"ingredient":"Yellow Pepper Diced, Blanched","lbs":0.125}] },
    { brand: "Lowe's", flavor: "7in White Spin", recipeName: "Lowes 7in White Spin", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":0.8}] },
    { brand: "Lowe's", flavor: "Bacon Cheeseburger", recipeName: "Lowes Bacon Cheeseburger", recipe: [{"ingredient":"Tomatoes","lbs":0.8},{"ingredient":"Bacon - NATURAL / tri meats tm3514u or / c&f 061anub40","lbs":0.5}] },
    { brand: "Lowe's", flavor: "California", recipeName: "Lowes California", recipe: [{"ingredient":"FR Tomatoes Diced","lbs":2.15},{"ingredient":"FR Red Pepper Strips","lbs":1.25},{"ingredient":"FR Red Onion Strips","lbs":0.6}] },
    { brand: "Lowe's", flavor: "Caribbean", recipeName: "Lowes Caribbean", recipe: [{"ingredient":"Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2}] },
    { brand: "Lowe's", flavor: "Chicken Club", recipeName: "Lowes Chicken Club", recipe: [{"ingredient":"Tomatoes, Diced","lbs":1.25},{"ingredient":"Bacon, NATURAL / tri meats tm3514u or / c&f 061anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.2}] },
    { brand: "Lowe's", flavor: "Grilled Vegetable", recipeName: "Lowes Grilled Vegetable", recipe: [{"ingredient":"FR Tomatoes Diced","lbs":2.02},{"ingredient":"FR Squash","lbs":0.71},{"ingredient":"FR Zucchini","lbs":0.71},{"ingredient":"Red Onions Diced","lbs":0.4},{"ingredient":"FR Garlic","lbs":0.1},{"ingredient":"Sea Salt","lbs":0.03},{"ingredient":"Thyme, IQF","lbs":0.03}] },
    { brand: "Lowe's", flavor: "Red Hot", recipeName: "Lowes Red Hot", recipe: [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / House of Raeford 28501 or / c&f 001mpdc40","lbs":2.43}] },
    { brand: "Lowe's", flavor: "Spinach", recipeName: "Lowes Spinach", recipe: [{"ingredient":"Spinach","lbs":2.3},{"ingredient":"Unsalted Butter","lbs":0.24},{"ingredient":"Salt","lbs":0.06},{"ingredient":"Egg","lbs":0.3},{"ingredient":"Garlic, Granulated","lbs":0.1}] },
    { brand: "Lowe's", flavor: "11in White Spinach", recipeName: "Lowes 11in White Spinach", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":2}] },
    { brand: "Lucia's", flavor: "Morning Melts Americano", recipeName: "Lucias Morning Melts Americano", recipe: [{"ingredient":"Diced Ham / patuxent-736543078","lbs":0.4},{"ingredient":"Scrambled Egg / Greand Prairie","lbs":0.6}] },
    { brand: "Lucia's", flavor: "Morming Melts Italiano", recipeName: "Lucias Morming Melts Italiano", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":2}] },
    { brand: "Lucia's", flavor: "Morning Melts Mexicano", recipeName: "Lucias Morning Melts Mexicano", recipe: [{"ingredient":"Scrambled Egg / Greand Prairie","lbs":0.6}] },
    { brand: "Lucia's", flavor: "Craft Alfredo Spinach", recipeName: "Lucias Craft Alfredo Spinach", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":0.98}] },
    { brand: "Lucia's", flavor: "Craft Bacon Cheeseburger", recipeName: "Lucias Craft Bacon Cheeseburger", recipe: [{"ingredient":"Diced Tomatoes","lbs":1.25},{"ingredient":"Bacon / Tri Meats tm3514u or / c&f 001anub40","lbs":0.5}] },
    { brand: "Lucia's", flavor: "Craft Bratwurst", recipeName: "Lucias Craft Bratwurst", recipe: [{"ingredient":"Sauerkraut **Drained**","lbs":1.3},{"ingredient":"Yellow Onion, FR Strips","lbs":0.75}] },
    { brand: "Lucia's", flavor: "Craft Caribbean", recipeName: "Lucias Craft Caribbean", recipe: [{"ingredient":"Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2}] },
    { brand: "Lucia's", flavor: "Craft Red Hot", recipeName: "Lucias Craft Red Hot", recipe: [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / c&f - 001mpdc40 or / House of Raeford - 28501","lbs":2.43}] },
    { brand: "Lucia's", flavor: "Craft SOB", recipeName: "Lucias Craft SOB", recipe: [{"ingredient":"Black Beans, IQF","lbs":0.74},{"ingredient":"Tomatoes, Diced","lbs":0.71},{"ingredient":"Red Onion, FR Strips","lbs":0.71},{"ingredient":"Corn, FR","lbs":0.63},{"ingredient":"Yellow Pepper Strips","lbs":0.46},{"ingredient":"Cilantro","lbs":0.11}] },
    { brand: "Lucia's", flavor: "Buffalo Chicken", recipeName: "Lucias Buffalo Chicken", recipe: [{"ingredient":"Diced Chicken / c&f 001mpdc40 or / House of Raeford 28501","lbs":2.4},{"ingredient":"Buffalo Sauce, Legacy","lbs":0.1}] },
    { brand: "Lucia's", flavor: "Supreme", recipeName: "Lucias Supreme", recipe: [{"ingredient":"Red Onion Strips, FR","lbs":0.75},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.75},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.75},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.75}] },
    { brand: "Lucia's", flavor: "Pinsa Margherita", recipeName: "Lucias Pinsa Margherita", recipe: [{"ingredient":"Goat Cheese","lbs":0.25}] },
    { brand: "Lucia's", flavor: "Pinsa Spinach", recipeName: "Lucias Pinsa Spinach", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":1}] },
    { brand: "Nob Hill", flavor: "SOB", recipeName: "Nob Hill SOB", recipe: [{"ingredient":"Black Beans, IQF","lbs":0.74},{"ingredient":"Tomatoes, Diced","lbs":0.71},{"ingredient":"Red Onion, FR Strips","lbs":0.71},{"ingredient":"Corn, FR","lbs":0.63},{"ingredient":"Yellow Pepper Strips","lbs":0.46},{"ingredient":"Cilantro","lbs":0.11}] },
    { brand: "Nob Hill", flavor: "Bacon Cheeseburger", recipeName: "Nob Hill Bacon Cheeseburger", recipe: [{"ingredient":"Diced Tomatoes","lbs":1.25},{"ingredient":"Bacon / Tri Meats tm3514u or / c&f 001anub40","lbs":0.5}] },
    { brand: "Nob Hill", flavor: "Red Hot", recipeName: "Nob Hill Red Hot", recipe: [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / c&f - 001mpdc40 or / House of Raeford - 28501","lbs":2.43}] },
    { brand: "Nob Hill", flavor: "Caribbean", recipeName: "Nob Hill Caribbean", recipe: [{"ingredient":"FR Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2}] },
    { brand: "Price Chopper", flavor: "Club", recipeName: "Price Chopper Club", recipe: [{"ingredient":"Bacon / Tri Meats tm3514u or / c&f 061anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}] },
    { brand: "SMD", flavor: "Supreme", recipeName: "SMD Supreme", recipe: [{"ingredient":"White Onion Strips, Blanched","lbs":0.35},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Black Olives","lbs":0.5}] },
  ],
};
