import type { RecipeRow } from "./types";

export type MixProfile = {
  brand: string;
  flavor: string;
  recipeName: string;
  recipe: RecipeRow[];
};

export const MIX_SEED: {
  brands: string[];
  brandFlavors: Record<string, string[]>;
  frontlineRecipeNames: string[];
  frontlineIngredients: string[];
  frontlineRecipePresets: Record<string, RecipeRow[]>;
  profiles: MixProfile[];
} = {
  brands: ["Basha","Bobo's","Corner Booth","Craft","Hannaford","Lowe's","Lucia's","Morning Melts","Nob Hill","Pinsa","Price Chopper","SMD"],

  brandFlavors: {
    "Bobo's": ["Deluxe","Breakfast"],
    "Basha": ["11' Hawaiian","12' Supreme"],
    "Corner Booth": ["Chicken Alfredo","Giardiniera","House","Pep & Jal","Spinach","Supreme"],
    "Hannaford": ["Tikka Masala","Spinach Goat Cheese","Club","4Meat"],
    "Lowe's": ["7in Red Fajita","7in White Spin","Bacon Cheeseburger","California","Caribbean","Chicken Club","Grilled Vegetable","Red Hot","Spinach","11in White Spinach"],
    "Craft": ["Alfredo Spinach","Bacon Cheeseburger","Bratwurst","Caribbean","Chicken Club","Red Hot","SOB","Tikka Masala"],
    "Morning Melts": ["Americano","Italiano","Mexicano","Parisian"],
    "Pinsa": ["Margherita","Spinach","Tikka Masala"],
    "Lucia's": ["Buffalo Chicken","Supreme"],
    "Nob Hill": ["SOB","Bacon Cheeseburger","Club","Red Hot","Caribbean"],
    "Price Chopper": ["Club"],
    "SMD": ["Supreme"],
  },

  frontlineRecipeNames: [
    "Bobo's Deluxe","Bobo's Breakfast","Basha 11' Hawaiian","Basha 12' Supreme",
    "Corner Booth Chicken Alfredo","Corner Booth Giardiniera","Corner Booth House",
    "Corner Booth Pep & Jal","Corner Booth Spinach","Corner Booth Supreme",
    "Hannaford Tikka Masala","Hannaford Spinach Goat Cheese","Hannaford Club","Hannaford 4Meat",
    "Lowe's 7in Red Fajita","Lowe's 7in White Spin","Lowe's Bacon Cheeseburger",
    "Lowe's California","Lowe's Caribbean","Lowe's Chicken Club","Lowe's Grilled Vegetable",
    "Lowe's Red Hot","Lowe's Spinach","Lowe's 11in White Spinach",
    "Morning Melts Americano","Morning Melts Italiano","Morning Melts Mexicano","Morning Melts Parisian",
    "Craft Alfredo Spinach","Craft Bacon Cheeseburger","Craft Bratwurst",
    "Craft Caribbean","Craft Chicken Club","Craft Red Hot","Craft SOB","Craft Tikka Masala",
    "Lucia's Buffalo Chicken","Lucia's Supreme",
    "Pinsa Margherita","Pinsa Spinach","Pinsa Tikka Masala",
    "Nob Hill SOB","Nob Hill Bacon Cheeseburger","Nob Hill Club","Nob Hill Red Hot","Nob Hill Caribbean",
    "Price Chopper Club","SMD Supreme",
  ],

  frontlineIngredients: [
    "Bacon - Cured / Tri Meats tm3514u or c&f 001anub40",
    "Bacon - Natural / Tri Meats tm3514u or c&f 061anub40",
    "Basil, Frozen","Black Beans, IQF","Black Olives","Buffalo Sauce, Legacy",
    "Canadian Bacon Stick / Stonie's - 2398","Diced Turkey / jennie-o-119373",
    "Drained Pineapples",
    "Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501",
    "Cilantro","Corn, FR",
    "Diced Ham / patuxent-736543078","Diced Tomatoes","Egg",
    "FR Garlic","FR Green Peppers Strip","FR Red Onion Strip","FR Red Onion Strips",
    "FR Red Pepper Strips","FR Squash","FR Tomatoes Diced","FR Zucchini",
    "Fresh Spinach (broken up)","Garlic Powder","Garlic sauce","Garlic, Granulated",
    "Goat Cheese","Green Onion","Masala Sauce","Green Pepper Diced, Blanched","Green Pepper Strips",
    "Green Pepper Strips, Blanched","Green Peppers, FR Strips","Hot Giardiniera Mix",
    "Hot Sauce, Old Vienna","Jalapenos","Mushrooms",
    "Natural Hamburger / burke 40029","Natural Italian Sausage / c&f 140mrp240",
    "Pineapple - Drained","Red Onion","Red Onion Diced, Blanched","Red Onion Strip",
    "Red Onion Strips, FR","Red Onion, FR Strips","Red Onions Diced",
    "Red Pepper Diced, Blanched","Red Pepper Strips","Red Pepper Strips, Blanched",
    "Red Peppers, FR Strips","Salt","Sauerkraut **Drained**",
    "Scrambled Egg / Greand Prairie","Sea Salt","Spinach","Swiss","Thyme, IQF",
    "Tomatoes","Tomatoes, Diced","Tomatoes, FR Diced","Unsalted Butter","White Onion Strips, Blanched",
    "Yellow Onion, FR Strips","Yellow Pepper Diced, Blanched","Yellow Pepper Strips",
    "Yellow Pepper Strips, Blanched",
  ],

  frontlineRecipePresets: {
    "Bobo's Deluxe": [{"ingredient":"Red Onion, FR Strips","lbs":0.4},{"ingredient":"Red Peppers, FR Strips","lbs":0.82},{"ingredient":"Green Peppers, FR Strips","lbs":0.82},{"ingredient":"Basil, Frozen","lbs":0.06},{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.75}],
    "Bobo's Breakfast": [{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.7}],
    "Basha 11' Hawaiian": [{"ingredient":"Pineapple - Drained","lbs":2},{"ingredient":"Canadian Bacon Stick / Stonie's - 2398","lbs":2}],
    "Basha 12' Supreme": [{"ingredient":"Red Onion","lbs":0.75},{"ingredient":"Green Pepper Strips","lbs":0.75},{"ingredient":"Red Pepper Strips","lbs":0.75},{"ingredient":"Yellow Pepper Strips","lbs":0.75}],
    "Corner Booth Chicken Alfredo": [{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2.98},{"ingredient":"Garlic Powder","lbs":0.02}],
    "Corner Booth Giardiniera": [{"ingredient":"Hot Giardiniera Mix","lbs":1.75}],
    "Corner Booth House": [{"ingredient":"White Onion Strips, Blanched","lbs":0.7},{"ingredient":"Green Pepper Strips, Blanched","lbs":1},{"ingredient":"Mushrooms","lbs":1}],
    "Corner Booth Pep & Jal": [{"ingredient":"Garlic sauce","lbs":4}],
    "Corner Booth Spinach": [{"ingredient":"Fresh Spinach (broken up)","lbs":1.75}],
    "Corner Booth Supreme": [{"ingredient":"White Onion Strips, Blanched","lbs":0.563},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.563},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.563},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.563}],
    "Hannaford Tikka Masala": [{"ingredient":"White Onion Strips, Blanched","lbs":0.375},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.375},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.375},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.375},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2},{"ingredient":"Masala Sauce","lbs":0.07}],
    "Hannaford Spinach Goat Cheese": [{"ingredient":"Fresh Spinach (broken up)","lbs":0.6},{"ingredient":"Goat Cheese","lbs":1}],
    "Hannaford Club": [{"ingredient":"Bacon - Natural / Tri Meats tm3514u or c&f 061anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}],
    "Hannaford 4Meat": [{"ingredient":"Natural Italian Sausage / c&f 140mrp240","lbs":1.5},{"ingredient":"Natural Hamburger / burke 40029","lbs":0.5}],
    "Lowe's 7in Red Fajita": [{"ingredient":"Red Onion Diced, Blanched","lbs":0.125},{"ingredient":"Green Pepper Diced, Blanched","lbs":0.125},{"ingredient":"Red Pepper Diced, Blanched","lbs":0.125},{"ingredient":"Yellow Pepper Diced, Blanched","lbs":0.125}],
    "Lowe's 7in White Spin": [{"ingredient":"Fresh Spinach (broken up)","lbs":0.8}],
    "Lowe's Bacon Cheeseburger": [{"ingredient":"Tomatoes","lbs":0.8},{"ingredient":"Bacon - Natural / Tri Meats tm3514u or c&f 061anub40","lbs":0.5}],
    "Lowe's California": [{"ingredient":"FR Tomatoes Diced","lbs":2.15},{"ingredient":"FR Red Pepper Strips","lbs":1.25},{"ingredient":"FR Red Onion Strips","lbs":0.6},{"ingredient":"Goat Cheese","lbs":1.01}],
    "Lowe's Caribbean": [{"ingredient":"Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2},{"ingredient":"Drained Pineapples","lbs":0.75}],
    "Lowe's Chicken Club": [{"ingredient":"Tomatoes, Diced","lbs":1.25},{"ingredient":"Bacon - Natural / Tri Meats tm3514u or c&f 061anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.2}],
    "Lowe's Grilled Vegetable": [{"ingredient":"FR Tomatoes Diced","lbs":2.02},{"ingredient":"FR Squash","lbs":0.71},{"ingredient":"FR Zucchini","lbs":0.71},{"ingredient":"Red Onions Diced","lbs":0.4},{"ingredient":"FR Garlic","lbs":0.1},{"ingredient":"Sea Salt","lbs":0.03},{"ingredient":"Thyme, IQF","lbs":0.03}],
    "Lowe's Red Hot": [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2.43}],
    "Lowe's Spinach": [{"ingredient":"Spinach","lbs":2.3},{"ingredient":"Unsalted Butter","lbs":0.24},{"ingredient":"Salt","lbs":0.06},{"ingredient":"Egg","lbs":0.3},{"ingredient":"Garlic, Granulated","lbs":0.1}],
    "Lowe's 11in White Spinach": [{"ingredient":"Fresh Spinach (broken up)","lbs":2}],
    "Morning Melts Americano": [{"ingredient":"Diced Ham / patuxent-736543078","lbs":0.4},{"ingredient":"Scrambled Egg / Greand Prairie","lbs":0.6}],
    "Morning Melts Italiano": [{"ingredient":"Fresh Spinach (broken up)","lbs":2}],
    "Morning Melts Mexicano": [{"ingredient":"Scrambled Egg / Greand Prairie","lbs":0.6}],
    "Craft Alfredo Spinach": [{"ingredient":"Fresh Spinach (broken up)","lbs":0.98}],
    "Craft Bacon Cheeseburger": [{"ingredient":"Diced Tomatoes","lbs":1.25},{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.5}],
    "Craft Bratwurst": [{"ingredient":"Sauerkraut **Drained**","lbs":1.3},{"ingredient":"Yellow Onion, FR Strips","lbs":0.75}],
    "Craft Caribbean": [{"ingredient":"Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2},{"ingredient":"Drained Pineapples","lbs":0.75}],
    "Craft Chicken Club": [{"ingredient":"Tomatoes, FR Diced","lbs":1},{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}],
    "Craft Red Hot": [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2.43}],
    "Craft SOB": [{"ingredient":"Black Beans, IQF","lbs":0.74},{"ingredient":"Tomatoes, Diced","lbs":0.71},{"ingredient":"Red Onion, FR Strips","lbs":0.71},{"ingredient":"Corn, FR","lbs":0.63},{"ingredient":"Yellow Pepper Strips","lbs":0.46},{"ingredient":"Cilantro","lbs":0.11}],
    "Lucia's Buffalo Chicken": [{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2.4},{"ingredient":"Buffalo Sauce, Legacy","lbs":0.1}],
    "Lucia's Supreme": [{"ingredient":"Red Onion Strips, FR","lbs":0.75},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.75},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.75},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.75}],
    "Craft Tikka Masala": [{"ingredient":"White Onion Strips, Blanched","lbs":0.37},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.37},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.39},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.37},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2},{"ingredient":"Masala Sauce","lbs":0.07}],
    "Morning Melts Parisian": [{"ingredient":"Diced Turkey / jennie-o-119373","lbs":0.2},{"ingredient":"Diced Ham / patuxent-736543078","lbs":0.2},{"ingredient":"Scrambled Egg / Greand Prairie","lbs":0.6},{"ingredient":"Swiss","lbs":0.75}],
    "Pinsa Margherita": [{"ingredient":"Goat Cheese","lbs":0.25}],
    "Pinsa Spinach": [{"ingredient":"Fresh Spinach (broken up)","lbs":1}],
    "Pinsa Tikka Masala": [{"ingredient":"White Onion Strips, Blanched","lbs":0.525},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.525},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.525},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.525},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":1.93},{"ingredient":"Masala Sauce","lbs":0.07}],
    "Nob Hill SOB": [{"ingredient":"Black Beans, IQF","lbs":0.74},{"ingredient":"Tomatoes, Diced","lbs":0.71},{"ingredient":"Red Onion, FR Strips","lbs":0.71},{"ingredient":"Corn, FR","lbs":0.63},{"ingredient":"Yellow Pepper Strips","lbs":0.46},{"ingredient":"Cilantro","lbs":0.11}],
    "Nob Hill Bacon Cheeseburger": [{"ingredient":"Diced Tomatoes","lbs":1.25},{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.5}],
    "Nob Hill Club": [{"ingredient":"Tomatoes, Diced","lbs":1},{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}],
    "Nob Hill Red Hot": [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2.43}],
    "Nob Hill Caribbean": [{"ingredient":"FR Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2},{"ingredient":"Drained Pineapples","lbs":0.75}],
    "Price Chopper Club": [{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}],
    "SMD Supreme": [{"ingredient":"White Onion Strips, Blanched","lbs":0.35},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Black Olives","lbs":0.5}],
  },

  profiles: [
    { brand: "Bobo's", flavor: "Deluxe", recipeName: "Bobo's Deluxe", recipe: [{"ingredient":"Red Onion, FR Strips","lbs":0.4},{"ingredient":"Red Peppers, FR Strips","lbs":0.82},{"ingredient":"Green Peppers, FR Strips","lbs":0.82},{"ingredient":"Basil, Frozen","lbs":0.06},{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.75}] },
    { brand: "Bobo's", flavor: "Breakfast", recipeName: "Bobo's Breakfast", recipe: [{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.7}] },
    { brand: "Basha", flavor: "11' Hawaiian", recipeName: "Basha 11' Hawaiian", recipe: [{"ingredient":"Pineapple - Drained","lbs":2},{"ingredient":"Canadian Bacon Stick / Stonie's - 2398","lbs":2}] },
    { brand: "Basha", flavor: "12' Supreme", recipeName: "Basha 12' Supreme", recipe: [{"ingredient":"Red Onion","lbs":0.75},{"ingredient":"Green Pepper Strips","lbs":0.75},{"ingredient":"Red Pepper Strips","lbs":0.75},{"ingredient":"Yellow Pepper Strips","lbs":0.75}] },
    { brand: "Corner Booth", flavor: "Chicken Alfredo", recipeName: "Corner Booth Chicken Alfredo", recipe: [{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2.98},{"ingredient":"Garlic Powder","lbs":0.02}] },
    { brand: "Corner Booth", flavor: "Giardiniera", recipeName: "Corner Booth Giardiniera", recipe: [{"ingredient":"Hot Giardiniera Mix","lbs":1.75}] },
    { brand: "Corner Booth", flavor: "House", recipeName: "Corner Booth House", recipe: [{"ingredient":"White Onion Strips, Blanched","lbs":0.7},{"ingredient":"Green Pepper Strips, Blanched","lbs":1},{"ingredient":"Mushrooms","lbs":1}] },
    { brand: "Corner Booth", flavor: "Pep & Jal", recipeName: "Corner Booth Pep & Jal", recipe: [{"ingredient":"Garlic sauce","lbs":4}] },
    { brand: "Corner Booth", flavor: "Spinach", recipeName: "Corner Booth Spinach", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":1.75}] },
    { brand: "Corner Booth", flavor: "Supreme", recipeName: "Corner Booth Supreme", recipe: [{"ingredient":"White Onion Strips, Blanched","lbs":0.563},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.563},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.563},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.563}] },
    { brand: "Hannaford", flavor: "Tikka Masala", recipeName: "Hannaford Tikka Masala", recipe: [{"ingredient":"White Onion Strips, Blanched","lbs":0.375},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.375},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.375},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.375},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2},{"ingredient":"Masala Sauce","lbs":0.07}] },
    { brand: "Hannaford", flavor: "Spinach Goat Cheese", recipeName: "Hannaford Spinach Goat Cheese", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":0.6},{"ingredient":"Goat Cheese","lbs":1}] },
    { brand: "Hannaford", flavor: "Club", recipeName: "Hannaford Club", recipe: [{"ingredient":"Bacon - Natural / Tri Meats tm3514u or c&f 061anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}] },
    { brand: "Hannaford", flavor: "4Meat", recipeName: "Hannaford 4Meat", recipe: [{"ingredient":"Natural Italian Sausage / c&f 140mrp240","lbs":1.5},{"ingredient":"Natural Hamburger / burke 40029","lbs":0.5}] },
    { brand: "Lowe's", flavor: "7in Red Fajita", recipeName: "Lowe's 7in Red Fajita", recipe: [{"ingredient":"Red Onion Diced, Blanched","lbs":0.125},{"ingredient":"Green Pepper Diced, Blanched","lbs":0.125},{"ingredient":"Red Pepper Diced, Blanched","lbs":0.125},{"ingredient":"Yellow Pepper Diced, Blanched","lbs":0.125}] },
    { brand: "Lowe's", flavor: "7in White Spin", recipeName: "Lowe's 7in White Spin", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":0.8}] },
    { brand: "Lowe's", flavor: "Bacon Cheeseburger", recipeName: "Lowe's Bacon Cheeseburger", recipe: [{"ingredient":"Tomatoes","lbs":0.8},{"ingredient":"Bacon - Natural / Tri Meats tm3514u or c&f 061anub40","lbs":0.5}] },
    { brand: "Lowe's", flavor: "California", recipeName: "Lowe's California", recipe: [{"ingredient":"FR Tomatoes Diced","lbs":2.15},{"ingredient":"FR Red Pepper Strips","lbs":1.25},{"ingredient":"FR Red Onion Strips","lbs":0.6},{"ingredient":"Goat Cheese","lbs":1.01}] },
    { brand: "Lowe's", flavor: "Caribbean", recipeName: "Lowe's Caribbean", recipe: [{"ingredient":"Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2},{"ingredient":"Drained Pineapples","lbs":0.75}] },
    { brand: "Lowe's", flavor: "Chicken Club", recipeName: "Lowe's Chicken Club", recipe: [{"ingredient":"Tomatoes, Diced","lbs":1.25},{"ingredient":"Bacon - Natural / Tri Meats tm3514u or c&f 061anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.2}] },
    { brand: "Lowe's", flavor: "Grilled Vegetable", recipeName: "Lowe's Grilled Vegetable", recipe: [{"ingredient":"FR Tomatoes Diced","lbs":2.02},{"ingredient":"FR Squash","lbs":0.71},{"ingredient":"FR Zucchini","lbs":0.71},{"ingredient":"Red Onions Diced","lbs":0.4},{"ingredient":"FR Garlic","lbs":0.1},{"ingredient":"Sea Salt","lbs":0.03},{"ingredient":"Thyme, IQF","lbs":0.03}] },
    { brand: "Lowe's", flavor: "Red Hot", recipeName: "Lowe's Red Hot", recipe: [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2.43}] },
    { brand: "Lowe's", flavor: "Spinach", recipeName: "Lowe's Spinach", recipe: [{"ingredient":"Spinach","lbs":2.3},{"ingredient":"Unsalted Butter","lbs":0.24},{"ingredient":"Salt","lbs":0.06},{"ingredient":"Egg","lbs":0.3},{"ingredient":"Garlic, Granulated","lbs":0.1}] },
    { brand: "Lowe's", flavor: "11in White Spinach", recipeName: "Lowe's 11in White Spinach", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":2}] },
    { brand: "Morning Melts", flavor: "Americano", recipeName: "Morning Melts Americano", recipe: [{"ingredient":"Diced Ham / patuxent-736543078","lbs":0.4},{"ingredient":"Scrambled Egg / Greand Prairie","lbs":0.6}] },
    { brand: "Morning Melts", flavor: "Italiano", recipeName: "Morning Melts Italiano", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":2}] },
    { brand: "Morning Melts", flavor: "Mexicano", recipeName: "Morning Melts Mexicano", recipe: [{"ingredient":"Scrambled Egg / Greand Prairie","lbs":0.6}] },
    { brand: "Morning Melts", flavor: "Parisian", recipeName: "Morning Melts Parisian", recipe: [{"ingredient":"Diced Turkey / jennie-o-119373","lbs":0.2},{"ingredient":"Diced Ham / patuxent-736543078","lbs":0.2},{"ingredient":"Scrambled Egg / Greand Prairie","lbs":0.6},{"ingredient":"Swiss","lbs":0.75}] },
    { brand: "Craft", flavor: "Alfredo Spinach", recipeName: "Craft Alfredo Spinach", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":0.98}] },
    { brand: "Craft", flavor: "Bacon Cheeseburger", recipeName: "Craft Bacon Cheeseburger", recipe: [{"ingredient":"Diced Tomatoes","lbs":1.25},{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.5}] },
    { brand: "Craft", flavor: "Bratwurst", recipeName: "Craft Bratwurst", recipe: [{"ingredient":"Sauerkraut **Drained**","lbs":1.3},{"ingredient":"Yellow Onion, FR Strips","lbs":0.75}] },
    { brand: "Craft", flavor: "Caribbean", recipeName: "Craft Caribbean", recipe: [{"ingredient":"Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2},{"ingredient":"Drained Pineapples","lbs":0.75}] },
    { brand: "Craft", flavor: "Chicken Club", recipeName: "Craft Chicken Club", recipe: [{"ingredient":"Tomatoes, FR Diced","lbs":1},{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}] },
    { brand: "Craft", flavor: "Red Hot", recipeName: "Craft Red Hot", recipe: [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2.43}] },
    { brand: "Craft", flavor: "SOB", recipeName: "Craft SOB", recipe: [{"ingredient":"Black Beans, IQF","lbs":0.74},{"ingredient":"Tomatoes, Diced","lbs":0.71},{"ingredient":"Red Onion, FR Strips","lbs":0.71},{"ingredient":"Corn, FR","lbs":0.63},{"ingredient":"Yellow Pepper Strips","lbs":0.46},{"ingredient":"Cilantro","lbs":0.11}] },
    { brand: "Lucia's", flavor: "Buffalo Chicken", recipeName: "Lucia's Buffalo Chicken", recipe: [{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2.4},{"ingredient":"Buffalo Sauce, Legacy","lbs":0.1}] },
    { brand: "Lucia's", flavor: "Supreme", recipeName: "Lucia's Supreme", recipe: [{"ingredient":"Red Onion Strips, FR","lbs":0.75},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.75},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.75},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.75}] },
    { brand: "Craft", flavor: "Tikka Masala", recipeName: "Craft Tikka Masala", recipe: [{"ingredient":"White Onion Strips, Blanched","lbs":0.37},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.37},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.39},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.37},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2},{"ingredient":"Masala Sauce","lbs":0.07}] },
    { brand: "Pinsa", flavor: "Margherita", recipeName: "Pinsa Margherita", recipe: [{"ingredient":"Goat Cheese","lbs":0.25}] },
    { brand: "Pinsa", flavor: "Spinach", recipeName: "Pinsa Spinach", recipe: [{"ingredient":"Fresh Spinach (broken up)","lbs":1}] },
    { brand: "Pinsa", flavor: "Tikka Masala", recipeName: "Pinsa Tikka Masala", recipe: [{"ingredient":"White Onion Strips, Blanched","lbs":0.525},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.525},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.525},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.525},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":1.93},{"ingredient":"Masala Sauce","lbs":0.07}] },
    { brand: "Nob Hill", flavor: "SOB", recipeName: "Nob Hill SOB", recipe: [{"ingredient":"Black Beans, IQF","lbs":0.74},{"ingredient":"Tomatoes, Diced","lbs":0.71},{"ingredient":"Red Onion, FR Strips","lbs":0.71},{"ingredient":"Corn, FR","lbs":0.63},{"ingredient":"Yellow Pepper Strips","lbs":0.46},{"ingredient":"Cilantro","lbs":0.11}] },
    { brand: "Nob Hill", flavor: "Bacon Cheeseburger", recipeName: "Nob Hill Bacon Cheeseburger", recipe: [{"ingredient":"Diced Tomatoes","lbs":1.25},{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.5}] },
    { brand: "Nob Hill", flavor: "Club", recipeName: "Nob Hill Club", recipe: [{"ingredient":"Tomatoes, Diced","lbs":1},{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}] },
    { brand: "Nob Hill", flavor: "Red Hot", recipeName: "Nob Hill Red Hot", recipe: [{"ingredient":"Hot Sauce, Old Vienna","lbs":0.07},{"ingredient":"Chicken, Diced / c&f 001mpdc40 or House of Raeford 28501","lbs":2.43}] },
    { brand: "Nob Hill", flavor: "Caribbean", recipeName: "Nob Hill Caribbean", recipe: [{"ingredient":"FR Red Onion Strip","lbs":0.7},{"ingredient":"FR Green Peppers Strip","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2},{"ingredient":"Drained Pineapples","lbs":0.75}] },
    { brand: "Price Chopper", flavor: "Club", recipeName: "Price Chopper Club", recipe: [{"ingredient":"Bacon - Cured / Tri Meats tm3514u or c&f 001anub40","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}] },
    { brand: "SMD", flavor: "Supreme", recipeName: "SMD Supreme", recipe: [{"ingredient":"White Onion Strips, Blanched","lbs":0.35},{"ingredient":"Green Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Red Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Yellow Pepper Strips, Blanched","lbs":0.35},{"ingredient":"Black Olives","lbs":0.5}] },
  ],
};
