import type { OperationalReport } from "@workspace/day-summary";
import * as XLSX from "xlsx";

function sectionValue<T>(
  section: { availability: string; value: T | null; note?: string },
  format: (value: T) => string,
): string {
  if (section.availability !== "available" || section.value === null) {
    return `Unavailable${section.note ? ` — ${section.note}` : ""}`;
  }
  return format(section.value);
}

export function operationalReportTitle(report: OperationalReport): string {
  return `Operational ${report.scope} report — ${report.periodStart} to ${report.periodEnd}`;
}

export type OperationalReportSource = "authoritative" | "local-offline";

export function operationalReportText(
  report: OperationalReport,
  source: OperationalReportSource = "authoritative",
): string {
  const p = report.production;
  const lines = [
    "OPERATIONAL PRODUCTION REPORT",
    `Scope: ${report.scope}`,
    `Period: ${report.periodStart} to ${report.periodEnd}`,
    `Scope date: ${report.date}`,
    `Generated: ${report.generatedAt}`,
    `Generated by: ${report.attribution?.generatedBy ?? "Unknown"}`,
    "",
    source === "authoritative"
      ? "AUTHORITATIVE SOURCE STATISTICS"
      : "LOCAL/OFFLINE FALLBACK — NOT AUTHORITATIVE",
    `Runs: ${p.runsFinished} finished of ${p.runsPlanned} planned`,
    `Cases: ${p.casesProduced} produced of ${p.casesPlanned} planned (${p.attainmentPct}% attainment)`,
    `Downtime: ${p.totalDowntimeMinutes} minutes across ${p.totalStoppages} stoppages`,
    `Unfinished runs: ${p.unfinishedRuns.length ? p.unfinishedRuns.join(", ") : "None recorded"}`,
    `Quality: ${sectionValue(report.quality, (value) => `${value.checks} checks, ${value.issues} issues, ${value.failed} failed, ${value.warnings} warnings`)}`,
    `Incidents: ${sectionValue(report.incidents, (value) => `${value.total} total, ${value.unresolved} unresolved`)}`,
    `Inventory flags: ${sectionValue(report.inventory, (value) => `${value.flaggedItems} items at or below reorder level`)}`,
    report.inventory.value?.historical
      ? `Historical inventory events: ${sectionValue(report.inventory.value.historical, (value) => `${value.totalEvents} total, ${value.consumptionEvents} consumption, ${value.wasteEvents} waste, ${value.adjustmentEvents} adjustments`)}`
      : "Historical inventory events: Unavailable",
    `Unresolved actions: ${sectionValue(report.unresolvedActions ?? { availability: "unavailable", value: null }, (value) => `${value.total} total`)}`,
  ];

  return lines.join("\n");
}

export async function shareOperationalReport(
  report: OperationalReport,
  source: OperationalReportSource = "authoritative",
): Promise<"shared" | "copied" | "failed"> {
  const text = operationalReportText(report, source);
  const title = operationalReportTitle(report);

  if (typeof navigator !== "undefined" && typeof navigator.share === "function") {
    try {
      await navigator.share({ title, text });
      return "shared";
    } catch (error) {
      if (error instanceof DOMException && error.name === "AbortError") {
        return "shared";
      }
    }
  }

  try {
    if (typeof navigator === "undefined" || !navigator.clipboard) return "failed";
    await navigator.clipboard.writeText(text);
    return "copied";
  } catch {
    return "failed";
  }
}

export type ReportExportKind = "csv" | "xlsx";

export function reportFilename(report: OperationalReport, kind: ReportExportKind | "txt" = "txt"): string {
  return `operational-${report.scope}-${report.date}.${kind}`;
}

type ExportRow = Record<string, string | number>;

export function operationalReportRows(report: OperationalReport): ExportRow[] {
  const rows: ExportRow[] = [];
  const add = (section: string, type: string, id: string, values: ExportRow) =>
    rows.push({ Section: section, "Row Type": type, ID: id, ...values });
  const unavailable = (section: string, availability: string, note?: string) =>
    add(section, "section-status", `${section.toLowerCase()}-status`, { Status: availability, Detail: note ?? "" });
  add("Report", "metadata", "report", {
    Period: `${report.periodStart} to ${report.periodEnd}`,
    Status: report.freshness?.status ?? "unknown",
    Detail: report.attribution?.generatedBy ?? "Unknown",
    Source: report.attribution?.source ?? "unknown",
  });
  add("Production", "summary", "production-summary", {
    "Cases Planned": report.production.casesPlanned,
    "Cases Produced": report.production.casesProduced,
    "Attainment %": report.production.attainmentPct,
    "Downtime Minutes": report.production.totalDowntimeMinutes,
    Stoppages: report.production.totalStoppages,
    Detail: report.calculation?.production ?? "",
  });
  if (!report.productionRows?.length) unavailable(
    "Production",
    "available-summary-only",
    "Production aggregates are available; no production detail rows were included.",
  );
  for (const row of report.productionRows ?? []) add("Production", "detail", row.id, {
    Date: row.date, Detail: row.run, Status: row.status, "Cases Planned": row.casesPlanned,
    "Cases Produced": row.casesProduced, "Attainment %": row.attainmentPct,
    "Downtime Minutes": row.downtimeMinutes, Stoppages: row.stoppages,
  });
  if (report.quality.availability !== "available" || !report.quality.value) unavailable("Quality", report.quality.availability, report.quality.note);
  else {
    if (!report.quality.value.rows?.length) unavailable("Quality", "available-no-detail-rows", report.quality.note ?? "No quality detail rows were recorded.");
    for (const row of report.quality.value.rows ?? []) add("Quality", "detail", row.id, {
      Date: row.occurredAt, Detail: `${row.product}: ${row.summary}`, Status: row.status, Issues: row.issues,
    });
  }
  if (report.incidents.availability !== "available" || !report.incidents.value) unavailable("Incidents", report.incidents.availability, report.incidents.note);
  else {
    if (!report.incidents.value.rows?.length) unavailable("Incidents", "available-no-detail-rows", report.incidents.note ?? "No incident detail rows were recorded.");
    for (const row of report.incidents.value.rows ?? []) add("Incidents", "detail", row.id, {
      Date: row.occurredAt, Detail: row.summary, Status: row.status, Priority: row.priority, Reporter: row.reporter,
    });
  }
  if (report.inventory.availability !== "available" || !report.inventory.value) unavailable("Inventory", report.inventory.availability, report.inventory.note);
  else {
    if (!report.inventory.value.rows?.length) unavailable("Inventory", "available-no-flagged-rows", report.inventory.note ?? "No inventory items were flagged.");
    for (const row of report.inventory.value.rows ?? []) add("Inventory", "detail", row.id, {
      Detail: row.item, Status: row.state, "On Hand": row.onHand, Unit: row.unit, "Reorder Threshold": row.reorderThreshold,
    });
  }
  if (report.unresolvedActions?.availability !== "available") unavailable("Actions", report.unresolvedActions?.availability ?? "unavailable", report.unresolvedActions?.note);
  else if (!report.unresolvedActions.value?.rows.length) unavailable("Actions", "available-no-open-rows", report.unresolvedActions.note ?? "No unresolved actions were identified.");
  if (report.unresolvedActions?.value) for (const row of report.unresolvedActions.value.rows) add("Actions", "detail", row.id, {
      Detail: `${row.action}: ${row.detail}`, Status: "open", Priority: row.priority, Source: row.source,
    });
  return rows;
}

function csvCell(value: string | number | undefined): string {
  const text = value === undefined ? "" : spreadsheetSafeValue(value);
  return `"${text.replace(/"/g, "\"\"")}"`;
}

function spreadsheetSafeValue(value: string | number): string {
  if (typeof value === "number") return String(value);
  return /^[=+\-@]/.test(value) ? `'${value}` : value;
}

export function operationalReportCsv(report: OperationalReport): string {
  const rows = operationalReportRows(report);
  const headers = Array.from(new Set(rows.flatMap((row) => Object.keys(row))));
  return [headers.map(csvCell).join(","), ...rows.map((row) => headers.map((key) => csvCell(row[key])).join(","))].join("\r\n");
}

export function operationalReportWorkbook(report: OperationalReport): XLSX.WorkBook {
  const workbook = XLSX.utils.book_new();
  const rows = operationalReportRows(report);
  for (const section of ["Report", "Production", "Quality", "Incidents", "Inventory", "Actions"]) {
    const safeRows = rows.filter((row) => row.Section === section).map((row) =>
      Object.fromEntries(Object.entries(row).map(([key, value]) => [
        key,
        typeof value === "string" ? spreadsheetSafeValue(value) : value,
      ])),
    );
    XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(safeRows), section);
  }
  return workbook;
}