import type { FormValues } from "./types";

  // AUTO-GENERATED from attached_assets/*.xlsx pizza spec sheets.
  // Sauce oz, applicator types/oz + sub-recipes, and pepperoni sticks/oz only.
  // Target weight & spec range are intentionally excluded.
  export type SpecProfile = { brand: string; flavor: string; values: Partial<FormValues> };

  export const SPEC_BRANDS: string[] = ["Aldo's","Basha","Bobo's","Brand","Corner Booth","Costco","Craft","FSD","Four Hands","Hannaford","Lowe's","Lucia's","Morning Melts","Nob Hill","Pinsa","Price Chopper","SMD"];

  export const SPEC_BRAND_FLAVORS: Record<string, string[]> = {
    "Aldo's": ["CHEESE","S & P","PEPPERONI","MEAT LOVER","SAUSAGE"],
  "Basha": ["CHEESE","PEPPERONI","SSG & PEPP","SUPREME"],
  "Bobo's": ["9\" CHEESE","12\" CHEESE","12\" BACON","12\" S & P","12\" DELUXE","12\" BUFFALO"],
  "Brand": ["MR12CH14","MR07CH24"],
  "Corner Booth": ["FIVE CHEESE","PEPPERONI","SUPREME","MEAT LOVER","WHITE SPINACH MUSHROOM","BUFFALO","BBQ CHICKEN","SAUSAGE & GIARDINIERA","SAUSAGE & PEPPERONI","HOUSE SPECIAL","PEPPERONI &\r\nJALAPENO","GARLIC CHICKEN\r\nALFREDO"],
  "Costco": ["THREE MEAT"],
  "Craft": ["CLUB","RED HOT CHICKEN","ALFREDO CHICKEN & SPINACH","BACON CHEESEBURGER","CARIBBEAN","BRAT","SOUTH OF THE BORDER","CHICKEN TIKKA MASALA"],
  "FSD": ["CHEESE","PEPPERONI","MEAT LOVERS","BREAKFAST"],
  "Four Hands": ["MEGA MEAT","OLD VIENNA RED HOT CHICKEN","CHICKEN BACON CLUB","SUGARFIRE BBQ CHICKEN","SEVEN CHEESE","MISSION TACO MEXICAN","MICHAEL'S GYRO","BACON CHEESEBURGER","CHICKEN TIKKA MASALA"],
  "Hannaford": ["FIVE CHEESE","BBQ CHICKEN","4 MEAT","FOUR CHEESE WITH SWEET & SPICY\r\nCHILI SAUCE","SPINACH GOAT CHEESE","CHICKEN BACON CLUB","CHICKEN TIKKA MASALA"],
  "Lowe's": ["FIVE CHEESE","MEAT LOVERS","PEPPERONI","SUPREME","BBQ CHICKEN","WHITE SPINACH"],
  "Lucia's": ["6CHEESE","PEPPERONI","SAUSAGE","SSG & PEPP","MEAT LOVERS","CHEESE BURGER","SUPREME","BUFFALO CHICKEN"],
  "Morning Melts": ["AMERICANO","ITALIANO","MEXICANO","PARISIAN"],
  "Nob Hill": ["SOUTH OF THE BORDER","BACON CHEESEBURGER","CLUB","RED HOT CHICKEN","CARIBBEAN"],
  "Pinsa": ["CHICKEN TIKKA MASALA","MARGHERITA","PEPPERONI","PESTO SPINACH"],
  "Price Chopper": ["BBQ CHICKEN","BUFFALO CHICKEN","Chicken Bacon Club","MEAT LOVERS"],
  "SMD": ["FOUR CHEESE","PEPPERONI","MEAT LOVERS","SUPREME","BBQ CHICKEN"],
  };

  export const SPEC_APP_TYPES: string[] = [
    "4Hands Club Mix",
  "4Hands Meat Cheese Mix",
  "4hands Red Hot Chicken Mix",
  "4Hands Red Hot Mix",
  "Aldo's Cheese Mix",
  "Bacon",
  "Bacon Cheeseburger Mix",
  "Basha's Original Cheese Mix",
  "BBQ Chicken Cheese Mix",
  "Beef Topping",
  "Bobo's Deluxe Vegetable Mix",
  "Brand Cheese Mix",
  "Bratwurst Mix",
  "Carribean Mix",
  "Celery",
  "Cheese Burger Cheese Mix",
  "Cheeseburger Cheese Mix",
  "Chicken Bacon Club Cheese Mix",
  "Chorizo",
  "Club Mix",
  "Corner Booth BBQ Chicken Cheese Mix",
  "Corner Booth Cheese Pizza Blend",
  "Corner Booth House Veggie Mix",
  "Corner Booth Pepperoni Cheese Blend",
  "Corner Booth Spinach Mushroom Cheese Mix",
  "Craft Cheeseburger Mix",
  "Deluxe Meat Mix",
  "Diced Blanched Red Pepper",
  "Diced Celery",
  "Diced Chicken",
  "Diced Ham",
  "Diced Red Fajita Mix",
  "Four Hands 7Cheese Mix",
  "Four Hands BBQ Chicken Cheese Mix",
  "Four Hands Mission Taco Mexican Mix",
  "Four Hands Red Hot Bacon Jalapeno Mix",
  "Four Hands Surgarfire Chicken Mix",
  "FR Red Onion Strips",
  "FSD Breakfast Meat Mix",
  "Garlic Chicken Mix",
  "Gyro Cheese Blend",
  "Gyro Meat Mix",
  "Gyro Veg Mix",
  "Hamburger",
  "Hannaford 4Meat Mix",
  "Hannaford Club Cheese Mix",
  "Hannaford Club Mix",
  "Hannaford South of Border Mix",
  "Hannaford Spinach Goat Cheese Mix",
  "Hannaford's Spicy 4Cheese Mix",
  "Hot Giardiniera Mix",
  "HT Standard Cheese Mix",
  "IQF Mushrooms",
  "Italian Sausage",
  "Jalapeno",
  "Lowe's Pepperoni Cheese Mix",
  "Lowe's Pepperoni/Romano Cheese Mix",
  "Lowe's Spinach Cheese Mix",
  "Lowe's/Hannaford 5Cheese Mix",
  "Lucia's Americano Cheese Mix",
  "Lucia's Club Cheese Mix",
  "Lucia's Craft Caribbean Cheese Mix",
  "Lucia's Craft Cheese Mix",
  "Lucia's Mexicano Cheese Mix",
  "Lucia's Parisian Meat Mix",
  "Lucia's Pepperoni Cheese Mix",
  "Lucia's Pinsa Pepperoni Cheese Mix",
  "Lucia's Pinsa Pepperoni/Romano Cheese Mix",
  "Lucia's Red Fajita Mix",
  "Lucia's Six Cheese Mix",
  "Lucia's Spinach Cheese Mix",
  "Lucia's Standard Cheese Mix",
  "Masala Chicken Mix",
  "Monterey Jack",
  "Monterey Jack Cheese",
  "Mozzarella Part Skim",
  "Natural Bacon",
  "Natural Hamburger",
  "Natural Italian Sausage",
  "Onion FR Diced White/Yellow",
  "Pineapple",
  "Pinsa Margherita Cheese Mix",
  "Pinsa Pesto Cheese Mix",
  "Pizella Cheese",
  "Red Fajita Mix",
  "Red Hot Cheese Mix",
  "Red Hot Cheese Mix Monterey Jack 5.0, Riplet Seasoning 0.01",
  "Red Hot Chicken Mix",
  "Red Onion Diced",
  "Red Onion, Diced",
  "Sausage",
  "Scrambled Egg",
  "Show Me Dough Supreme Mix",
  "SMD BBQ Chicken Cheese Mix",
  "SMD Four Cheese Mix",
  "SMD Pep Cheese Mix",
  "Spicy Breakfast Sausage",
  "STL Style Cheese",
  "Swiss Cheese",
  "Tomatoes",
  "Vita Lucia's Italiano Cheese Mix",
  "White Fajita Mix",
  "Whole Milk Mozzarella",
  "Whole Milk Mozzarella Cheese",
  "Whole Mozzarella",
  ];

  export const SPEC_PEP_TYPES: string[] = ["Bratwurst Sticks","Chorizo Stick","Diced Pepperoni","Mozzarella Stick","Pepperoni Stick","Pepperoni Stick - NATURAL"];

  export const SPEC_CHEESE_INGREDIENTS: string[] = [
    "Bacon",
  "Black Olives",
  "Blanched Green Pepper Strips",
  "Blanched Red Pepper Strips",
  "Blanched White Onion Strips",
  "Blanched Yellow Pepper Strips",
  "Cheese Spice Blend",
  "Chicken",
  "Chicken w",
  "Cilanto",
  "Cilantro",
  "COW Romano Cheese",
  "Cow's Romano",
  "Diced Chicken",
  "Diced Ham",
  "Diced Pepperoni",
  "Diced Tomatoes",
  "Diced Turkey",
  "Feta",
  "Fontina",
  "FR Corn",
  "FR Diced Tomatoes",
  "FR Green Pepper Strips",
  "FR Red Onion Strips",
  "FR Red Pepper Strips",
  "FR White Onion Strips",
  "FR Yellow Onion Strips",
  "Fresh Spinach",
  "Frozen Basil Flakes",
  "Garlic Powder",
  "Goat",
  "Goat Cheese",
  "Grated Parmesan",
  "Green Onion",
  "Green Pepper Strips",
  "Green Pepper Strips Blanched",
  "Gyro Meat",
  "Gyro Spice Blend",
  "IQF Basil",
  "IQF Black Beans",
  "IQF Cilantro",
  "Jalapenos",
  "Liquid Smoke",
  "Masala Sauce",
  "Monterey Jack",
  "Mushrooms",
  "Natural Hamburger",
  "Natural Italian Sausage",
  "Nutmeg",
  "Old Vienna Red Hot Riplet Seasoning",
  "Oregano Flake",
  "P/S Mozz",
  "Parmesan",
  "Part Skim Mozzarella",
  "Part-Skim Mozz",
  "Pizella",
  "Provolone",
  "Red Onion Strips",
  "Red Onions",
  "Red Pepper Strips",
  "Red Pepper Strips Blanched",
  "Sauerkraut",
  "Sausage",
  "SHEEP Romano",
  "Shredded Parmesan",
  "Skim Mozz",
  "Skim Mozzarella",
  "Spinach",
  "Three Cheese Blend",
  "Three Cheese Blend &",
  "Tomatoes",
  "Vienna Red Hot Sauce",
  "White Cheddar",
  "White Fajita Blend",
  "White Fajita Mix",
  "White Onion Strips",
  "White Onion Strips Blanched",
  "Whole Milk Mozzarella",
  "Whole Mozz",
  "Whole Mozzarella",
  "Whole Mozzarella-Extra Large Cut",
  "Yellow Cheddar",
  "Yellow Cheddar Cheese",
  "Yellow Pepper Strips",
  "Yellow Pepper Strips Blanched",
  ];

  export const SPEC_PROFILES: SpecProfile[] = [
    { brand: "Aldo's", flavor: "CHEESE", values: {
    sauceOzPerPizza: 4,
    app1Type: "Aldo's Cheese Mix",
    app1OzPerPizza: 3.65,
    app1CheeseRecipe: [{"ingredient":"Pizella","lbs":2.07},{"ingredient":"Part Skim Mozzarella","lbs":1.19},{"ingredient":"Grated Parmesan","lbs":0.26},{"ingredient":"Oregano Flake","lbs":0.13}],
    app1CheeseRecipeName: "Aldo's Cheese Mix",
    app2Type: "Aldo's Cheese Mix",
    app2OzPerPizza: 3.65,
    app2CheeseRecipe: [{"ingredient":"Pizella","lbs":2.07},{"ingredient":"Part Skim Mozzarella","lbs":1.19},{"ingredient":"Grated Parmesan","lbs":0.26},{"ingredient":"Oregano Flake","lbs":0.13}],
    app2CheeseRecipeName: "Aldo's Cheese Mix"
  } },
  { brand: "Aldo's", flavor: "S & P", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 13,
    pep1OzPerPizza: 1.1,
    pep1Type: "Pepperoni Stick",
    app1Type: "Sausage",
    app1OzPerPizza: 2.5,
    app2Type: "Aldo's Cheese Mix",
    app2OzPerPizza: 2.9,
    app2CheeseRecipe: [{"ingredient":"Pizella","lbs":1.75},{"ingredient":"Part Skim Mozzarella","lbs":1},{"ingredient":"Grated Parmesan","lbs":0.1},{"ingredient":"Oregano Flake","lbs":0.05}],
    app2CheeseRecipeName: "Aldo's Cheese Mix",
    app3Type: "Aldo's Cheese Mix",
    app3OzPerPizza: 2.9,
    app3CheeseRecipe: [{"ingredient":"Pizella","lbs":1.75},{"ingredient":"Part Skim Mozzarella","lbs":1},{"ingredient":"Grated Parmesan","lbs":0.1},{"ingredient":"Oregano Flake","lbs":0.05}],
    app3CheeseRecipeName: "Aldo's Cheese Mix"
  } },
  { brand: "Aldo's", flavor: "PEPPERONI", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 19,
    pep1OzPerPizza: 1.9,
    pep1Type: "Pepperoni Stick",
    app1Type: "Aldo's Cheese Mix",
    app1OzPerPizza: 2.9,
    app1CheeseRecipe: [{"ingredient":"Pizella","lbs":1.75},{"ingredient":"Part Skim Mozzarella","lbs":1},{"ingredient":"Grated Parmesan","lbs":0.1},{"ingredient":"Oregano Flake","lbs":0.05}],
    app1CheeseRecipeName: "Aldo's Cheese Mix",
    app2Type: "Aldo's Cheese Mix",
    app2OzPerPizza: 2.9,
    app2CheeseRecipe: [{"ingredient":"Pizella","lbs":1.75},{"ingredient":"Part Skim Mozzarella","lbs":1},{"ingredient":"Grated Parmesan","lbs":0.1},{"ingredient":"Oregano Flake","lbs":0.05}],
    app2CheeseRecipeName: "Aldo's Cheese Mix"
  } },
  { brand: "Aldo's", flavor: "MEAT LOVER", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 13,
    pep1OzPerPizza: 1.1,
    pep1Type: "Pepperoni Stick",
    app1Type: "Sausage",
    app1OzPerPizza: 2.25,
    app2Type: "Aldo's Cheese Mix",
    app2OzPerPizza: 2.9,
    app2CheeseRecipe: [{"ingredient":"Pizella","lbs":1.75},{"ingredient":"Part Skim Mozzarella","lbs":1},{"ingredient":"Grated Parmesan","lbs":0.1},{"ingredient":"Oregano Flake","lbs":0.05}],
    app2CheeseRecipeName: "Aldo's Cheese Mix",
    app3Type: "Bacon",
    app3OzPerPizza: 1.2,
    app4Type: "Aldo's Cheese Mix",
    app4OzPerPizza: 2.9,
    app4CheeseRecipe: [{"ingredient":"Pizella","lbs":1.75},{"ingredient":"Part Skim Mozzarella","lbs":1},{"ingredient":"Grated Parmesan","lbs":0.1},{"ingredient":"Oregano Flake","lbs":0.05}],
    app4CheeseRecipeName: "Aldo's Cheese Mix"
  } },
  { brand: "Aldo's", flavor: "SAUSAGE", values: {
    sauceOzPerPizza: 4,
    app1Type: "Sausage",
    app1OzPerPizza: 3,
    app2Type: "Aldo's Cheese Mix",
    app2OzPerPizza: 2.9,
    app2CheeseRecipe: [{"ingredient":"Pizella","lbs":1.75},{"ingredient":"Part Skim Mozzarella","lbs":1},{"ingredient":"Grated Parmesan","lbs":0.1},{"ingredient":"Oregano Flake","lbs":0.05}],
    app2CheeseRecipeName: "Aldo's Cheese Mix",
    app3Type: "Aldo's Cheese Mix",
    app3OzPerPizza: 2.9,
    app3CheeseRecipe: [{"ingredient":"Pizella","lbs":1.75},{"ingredient":"Part Skim Mozzarella","lbs":1},{"ingredient":"Grated Parmesan","lbs":0.1},{"ingredient":"Oregano Flake","lbs":0.05}],
    app3CheeseRecipeName: "Aldo's Cheese Mix"
  } },
  { brand: "Basha", flavor: "CHEESE", values: {
    sauceOzPerPizza: 4,
    app1Type: "Basha's Original Cheese Mix",
    app1OzPerPizza: 3,
    app1CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":2},{"ingredient":"Provolone","lbs":1}],
    app1CheeseRecipeName: "Basha's Original Cheese Mix",
    app2Type: "Basha's Original Cheese Mix",
    app2OzPerPizza: 3,
    app2CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":2},{"ingredient":"Provolone","lbs":1}],
    app2CheeseRecipeName: "Basha's Original Cheese Mix"
  } },
  { brand: "Basha", flavor: "PEPPERONI", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 19,
    pep1OzPerPizza: 1.5,
    pep1Type: "Pepperoni Stick",
    app1Type: "Whole Milk Mozzarella",
    app1OzPerPizza: 2.5,
    app2Type: "Whole Milk Mozzarella",
    app2OzPerPizza: 3
  } },
  { brand: "Basha", flavor: "SSG & PEPP", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 19,
    pep1OzPerPizza: 1.1,
    pep1Type: "Pepperoni Stick",
    app1Type: "Sausage",
    app1OzPerPizza: 2.5,
    app2Type: "Whole Milk Mozzarella",
    app2OzPerPizza: 3,
    app3Type: "Whole Milk Mozzarella",
    app3OzPerPizza: 2
  } },
  { brand: "Basha", flavor: "SUPREME", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 12,
    pep1OzPerPizza: 0.8,
    pep1Type: "Pepperoni Stick",
    app1Type: "Sausage",
    app1OzPerPizza: 1.7,
    app2Type: "Whole Milk Mozzarella",
    app2OzPerPizza: 2.5,
    app3Type: "Red Fajita Mix",
    app3OzPerPizza: 3,
    app3CheeseRecipe: [{"ingredient":"Red Onions","lbs":0.75},{"ingredient":"Green Pepper Strips","lbs":0.75},{"ingredient":"Red Pepper Strips","lbs":0.75},{"ingredient":"Yellow Pepper Strips","lbs":0.75}],
    app3CheeseRecipeName: "Red Fajita Mix",
    app4Type: "Whole Milk Mozzarella",
    app4OzPerPizza: 2
  } },
  { brand: "Bobo's", flavor: "9\" CHEESE", values: {
    sauceOzPerPizza: 2.25,
    app1Type: "STL Style Cheese",
    app1OzPerPizza: 3
  } },
  { brand: "Bobo's", flavor: "12\" CHEESE", values: {
    sauceOzPerPizza: 4,
    app1Type: "STL Style Cheese",
    app1OzPerPizza: 2.5,
    app2Type: "STL Style Cheese",
    app2OzPerPizza: 2.5
  } },
  { brand: "Bobo's", flavor: "12\" BACON", values: {
    sauceOzPerPizza: 4,
    app1Type: "STL Style Cheese",
    app1OzPerPizza: 2.5,
    app2Type: "Bacon",
    app2OzPerPizza: 2.5,
    app3Type: "STL Style Cheese",
    app3OzPerPizza: 2
  } },
  { brand: "Bobo's", flavor: "12\" S & P", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 15,
    pep1OzPerPizza: 1,
    pep1Type: "Pepperoni Stick",
    app1Type: "Sausage",
    app1OzPerPizza: 3,
    app2Type: "STL Style Cheese",
    app2OzPerPizza: 2.5,
    app3Type: "STL Style Cheese",
    app3OzPerPizza: 2
  } },
  { brand: "Bobo's", flavor: "12\" DELUXE", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 13,
    pep1OzPerPizza: 0.8,
    pep1Type: "Pepperoni Stick",
    app1Type: "Deluxe Meat Mix",
    app1OzPerPizza: 2.35,
    app1CheeseRecipe: [{"ingredient":"Sausage","lbs":2.35}],
    app1CheeseRecipeName: "Deluxe Meat Mix",
    app2Type: "STL Style Cheese",
    app2OzPerPizza: 2.5,
    app3Type: "Bobo's Deluxe Vegetable Mix",
    app3OzPerPizza: 2.85,
    app3CheeseRecipe: [{"ingredient":"FR Red Pepper Strips","lbs":0.82},{"ingredient":"FR Green Pepper Strips","lbs":0.82},{"ingredient":"Bacon","lbs":0.75},{"ingredient":"FR Red Onion Strips","lbs":0.4},{"ingredient":"Frozen Basil Flakes","lbs":0.06}],
    app3CheeseRecipeName: "Bobo's Deluxe Vegetable Mix",
    app4Type: "STL Style Cheese",
    app4OzPerPizza: 2
  } },
  { brand: "Bobo's", flavor: "12\" BUFFALO", values: {
    sauceOzPerPizza: 3,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 3.25,
    app2Type: "STL Style Cheese",
    app2OzPerPizza: 4.5
  } },
  { brand: "Brand", flavor: "MR12CH14", values: {
    sauceOzPerPizza: 3,
    app1Type: "Brand Cheese Mix",
    app1OzPerPizza: 2.5,
    app1CheeseRecipe: [{"ingredient":"Part Skim Mozzarella","lbs":1.25},{"ingredient":"Whole Mozzarella","lbs":1.25}],
    app1CheeseRecipeName: "Brand Cheese Mix",
    app2Type: "Brand Cheese Mix",
    app2OzPerPizza: 2.5,
    app2CheeseRecipe: [{"ingredient":"Part Skim Mozzarella","lbs":1.25},{"ingredient":"Whole Mozzarella","lbs":1.25}],
    app2CheeseRecipeName: "Brand Cheese Mix"
  } },
  { brand: "Brand", flavor: "MR07CH24", values: {
    sauceOzPerPizza: 1.5,
    app1Type: "Brand Cheese Mix",
    app1OzPerPizza: 2,
    app1CheeseRecipe: [{"ingredient":"Part Skim Mozzarella","lbs":1},{"ingredient":"Whole Mozzarella","lbs":1}],
    app1CheeseRecipeName: "Brand Cheese Mix"
  } },
  { brand: "Corner Booth", flavor: "FIVE CHEESE", values: {
    sauceOzPerPizza: 6,
    pep1Sticks: 9,
    pep1OzPerPizza: 1.25,
    pep1Type: "Mozzarella Stick",
    app1Type: "Corner Booth Cheese Pizza Blend",
    app1OzPerPizza: 3.75,
    app1CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":2.15},{"ingredient":"Yellow Cheddar","lbs":0.49},{"ingredient":"Provolone","lbs":0.65},{"ingredient":"Fontina","lbs":0.23},{"ingredient":"Grated Parmesan","lbs":0.23}],
    app1CheeseRecipeName: "Corner Booth Cheese Pizza Blend",
    app2Type: "Corner Booth Cheese Pizza Blend",
    app2OzPerPizza: 2,
    app2CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":1.15},{"ingredient":"Yellow Cheddar","lbs":0.26},{"ingredient":"Provolone","lbs":0.35},{"ingredient":"Fontina","lbs":0.12},{"ingredient":"Grated Parmesan","lbs":0.12}],
    app2CheeseRecipeName: "Corner Booth Cheese Pizza Blend"
  } },
  { brand: "Corner Booth", flavor: "PEPPERONI", values: {
    sauceOzPerPizza: 6,
    pep1Sticks: 24,
    pep1OzPerPizza: 2,
    pep1Type: "Pepperoni Stick",
    app1Type: "Corner Booth Pepperoni Cheese Blend",
    app1OzPerPizza: 4.25,
    app1CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":3.15},{"ingredient":"Provolone","lbs":0.83},{"ingredient":"Cow's Romano","lbs":0.27}],
    app1CheeseRecipeName: "Corner Booth Pepperoni Cheese Blend",
    app2Type: "Corner Booth Pepperoni Cheese Blend",
    app2OzPerPizza: 4,
    app2CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":2.97},{"ingredient":"Provolone","lbs":0.78},{"ingredient":"Cow's Romano","lbs":0.25}],
    app2CheeseRecipeName: "Corner Booth Pepperoni Cheese Blend"
  } },
  { brand: "Corner Booth", flavor: "SUPREME", values: {
    sauceOzPerPizza: 6,
    pep1Sticks: 11,
    pep1OzPerPizza: 0.75,
    pep1Type: "Pepperoni Stick",
    app1Type: "Italian Sausage",
    app1OzPerPizza: 2.5,
    app2Type: "Whole Mozzarella",
    app2OzPerPizza: 3,
    app3Type: "White Fajita Mix",
    app3OzPerPizza: 2.25,
    app3CheeseRecipe: [{"ingredient":"Blanched White Onion Strips","lbs":0.563},{"ingredient":"Blanched Green Pepper Strips","lbs":0.563},{"ingredient":"Blanched Red Pepper Strips","lbs":0.563},{"ingredient":"Blanched Yellow Pepper Strips","lbs":0.563}],
    app3CheeseRecipeName: "White Fajita Mix",
    app4Type: "Whole Mozzarella",
    app4OzPerPizza: 2
  } },
  { brand: "Corner Booth", flavor: "MEAT LOVER", values: {
    sauceOzPerPizza: 6,
    pep1Sticks: 19,
    pep1OzPerPizza: 1.5,
    pep1Type: "Pepperoni Stick",
    app1Type: "Italian Sausage",
    app1OzPerPizza: 3,
    app2Type: "Whole Mozzarella",
    app2OzPerPizza: 3,
    app3Type: "Bacon",
    app3OzPerPizza: 0.75,
    app4Type: "Whole Mozzarella",
    app4OzPerPizza: 2
  } },
  { brand: "Corner Booth", flavor: "WHITE SPINACH MUSHROOM", values: {
    sauceOzPerPizza: 4.5,
    app1Type: "Whole Mozzarella",
    app1OzPerPizza: 5,
    app2Type: "IQF Mushrooms",
    app2OzPerPizza: 2,
    app3Type: "Corner Booth Spinach Mushroom Cheese Mix",
    app3OzPerPizza: 4.01,
    app3CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":2},{"ingredient":"Fresh Spinach","lbs":1.75},{"ingredient":"Grated Parmesan","lbs":0.25},{"ingredient":"Nutmeg","lbs":0.01}],
    app3CheeseRecipeName: "Corner Booth Spinach Mushroom Cheese Mix"
  } },
  { brand: "Corner Booth", flavor: "BUFFALO", values: {
    sauceOzPerPizza: 4,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 3,
    app2Type: "Monterey Jack",
    app2OzPerPizza: 2.75,
    app3Type: "Monterey Jack",
    app3OzPerPizza: 2.75
  } },
  { brand: "Corner Booth", flavor: "BBQ CHICKEN", values: {
    sauceOzPerPizza: 4.5,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 3,
    app2Type: "Monterey Jack",
    app2OzPerPizza: 3,
    app3Type: "FR Red Onion Strips",
    app3OzPerPizza: 1,
    app4Type: "Corner Booth BBQ Chicken Cheese Mix",
    app4OzPerPizza: 3.9,
    app4CheeseRecipe: [{"ingredient":"Monterey Jack","lbs":3.8},{"ingredient":"Cilantro","lbs":0.1}],
    app4CheeseRecipeName: "Corner Booth BBQ Chicken Cheese Mix"
  } },
  { brand: "Corner Booth", flavor: "SAUSAGE & GIARDINIERA", values: {
    sauceOzPerPizza: 6,
    app1Type: "Italian Sausage",
    app1OzPerPizza: 4,
    app2Type: "Whole Mozzarella",
    app2OzPerPizza: 3,
    app3Type: "Hot Giardiniera Mix",
    app3OzPerPizza: 1.75,
    app4Type: "Whole Mozzarella",
    app4OzPerPizza: 2
  } },
  { brand: "Corner Booth", flavor: "SAUSAGE & PEPPERONI", values: {
    sauceOzPerPizza: 6,
    pep1Sticks: 12,
    pep1OzPerPizza: 1,
    pep1Type: "Pepperoni Stick",
    app1Type: "Italian Sausage",
    app1OzPerPizza: 3,
    app2Type: "Whole Mozzarella",
    app2OzPerPizza: 3,
    app3Type: "Whole Mozzarella",
    app3OzPerPizza: 2
  } },
  { brand: "Corner Booth", flavor: "HOUSE SPECIAL", values: {
    sauceOzPerPizza: 6,
    app1Type: "Italian Sausage",
    app1OzPerPizza: 2.5,
    app2Type: "Whole Mozzarella",
    app2OzPerPizza: 3,
    app3Type: "Corner Booth House Veggie Mix",
    app3OzPerPizza: 2.7,
    app3CheeseRecipe: [{"ingredient":"Blanched Green Pepper Strips","lbs":1},{"ingredient":"Mushrooms","lbs":1},{"ingredient":"Blanched White Onion Strips","lbs":0.7}],
    app3CheeseRecipeName: "Corner Booth House Veggie Mix",
    app4Type: "Whole Mozzarella",
    app4OzPerPizza: 2
  } },
  { brand: "Corner Booth", flavor: "PEPPERONI &\r\nJALAPENO", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 18,
    pep1OzPerPizza: 1.5,
    pep1Type: "Pepperoni Stick",
    app1Type: "Corner Booth Pepperoni Cheese Blend",
    app1OzPerPizza: 4,
    app1CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":3},{"ingredient":"Provolone","lbs":0.7},{"ingredient":"Cow's Romano","lbs":0.3}],
    app1CheeseRecipeName: "Corner Booth Pepperoni Cheese Blend",
    app2Type: "Jalapeno",
    app2OzPerPizza: 1,
    app3Type: "Corner Booth Pepperoni Cheese Blend",
    app3OzPerPizza: 2,
    app3CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":1.5},{"ingredient":"Provolone","lbs":0.4},{"ingredient":"Cow's Romano","lbs":0.1}],
    app3CheeseRecipeName: "Corner Booth Pepperoni Cheese Blend"
  } },
  { brand: "Corner Booth", flavor: "GARLIC CHICKEN\r\nALFREDO", values: {
    sauceOzPerPizza: 3.5,
    app1Type: "Whole Mozzarella",
    app1OzPerPizza: 4,
    app2Type: "Garlic Chicken Mix",
    app2OzPerPizza: 3,
    app2CheeseRecipe: [{"ingredient":"Garlic Powder","lbs":0.02}],
    app2CheeseRecipeName: "Garlic Chicken Mix",
    app3Type: "Whole Mozzarella",
    app3OzPerPizza: 2
  } },
  { brand: "Costco", flavor: "THREE MEAT", values: {
    sauceOzPerPizza: 6,
    pep1Sticks: 17,
    pep1OzPerPizza: 1.2,
    pep1Type: "Pepperoni Stick",
    app1Type: "Italian Sausage",
    app1OzPerPizza: 3.5,
    app2Type: "Pizella Cheese",
    app2OzPerPizza: 4,
    app3Type: "Bacon",
    app3OzPerPizza: 1.3,
    app4Type: "Pizella Cheese",
    app4OzPerPizza: 2
  } },
  { brand: "FSD", flavor: "CHEESE", values: {
    sauceOzPerPizza: 1.5,
    app1Type: "Whole Mozzarella",
    app1OzPerPizza: 1.5
  } },
  { brand: "FSD", flavor: "PEPPERONI", values: {
    sauceOzPerPizza: 1.5,
    pep1Sticks: 0,
    pep1OzPerPizza: 0.5,
    pep1Type: "Diced Pepperoni",
    app1Type: "Whole Mozzarella",
    app1OzPerPizza: 1
  } },
  { brand: "FSD", flavor: "MEAT LOVERS", values: {
    sauceOzPerPizza: 1.5,
    pep1Sticks: 0,
    pep1OzPerPizza: 0.2,
    pep1Type: "Diced Pepperoni",
    app1Type: "Italian Sausage",
    app1OzPerPizza: 0.75,
    app2Type: "Bacon",
    app2OzPerPizza: 0.1,
    app3Type: "Whole Mozzarella",
    app3OzPerPizza: 1
  } },
  { brand: "FSD", flavor: "BREAKFAST", values: {
    sauceOzPerPizza: 1.3,
    app1Type: "Scrambled Egg",
    app1OzPerPizza: 1,
    app2Type: "Spicy Breakfast Sausage",
    app2OzPerPizza: 0.5,
    app3Type: "FSD Breakfast Meat Mix",
    app3OzPerPizza: 0.4,
    app3CheeseRecipe: [{"ingredient":"Diced Ham","lbs":0.2},{"ingredient":"Bacon","lbs":0.2}],
    app3CheeseRecipeName: "FSD Breakfast Meat Mix",
    app4Type: "Lucia's Americano Cheese Mix",
    app4OzPerPizza: 1,
    app4CheeseRecipe: [{"ingredient":"Skim Mozzarella","lbs":0.5},{"ingredient":"Yellow Cheddar","lbs":0.5}],
    app4CheeseRecipeName: "Lucia's Americano Cheese Mix"
  } },
  { brand: "Four Hands", flavor: "MEGA MEAT", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 13,
    pep1OzPerPizza: 1,
    pep1Type: "Pepperoni Stick",
    app1Type: "Italian Sausage",
    app1OzPerPizza: 2,
    app2Type: "4Hands Meat Cheese Mix",
    app2OzPerPizza: 2.5,
    app2CheeseRecipe: [{"ingredient":"Part-Skim Mozz","lbs":2.09},{"ingredient":"White Cheddar","lbs":0.22},{"ingredient":"Provolone","lbs":0.19}],
    app2CheeseRecipeName: "4Hands Meat Cheese Mix",
    app3Type: "Bacon",
    app3OzPerPizza: 0.5,
    app4Type: "4Hands Meat Cheese Mix",
    app4OzPerPizza: 1.5,
    app4CheeseRecipe: [{"ingredient":"Part-Skim Mozz","lbs":1.26},{"ingredient":"White Cheddar","lbs":0.13},{"ingredient":"Provolone","lbs":0.11}],
    app4CheeseRecipeName: "4Hands Meat Cheese Mix"
  } },
  { brand: "Four Hands", flavor: "OLD VIENNA RED HOT CHICKEN", values: {
    sauceOzPerPizza: 3,
    app1Type: "Red Hot Chicken Mix",
    app1OzPerPizza: 2.5,
    app1CheeseRecipe: [{"ingredient":"Chicken w","lbs":2.41},{"ingredient":"Vienna Red Hot Sauce","lbs":0.09}],
    app1CheeseRecipeName: "Red Hot Chicken Mix",
    app2Type: "Four Hands Red Hot Bacon Jalapeno Mix",
    app2OzPerPizza: 0.75,
    app2CheeseRecipe: [{"ingredient":"Bacon","lbs":0.49},{"ingredient":"Jalapenos","lbs":0.24}],
    app2CheeseRecipeName: "Four Hands Red Hot Bacon Jalapeno Mix",
    app3Type: "Red Hot Cheese Mix",
    app3OzPerPizza: 5.01,
    app3CheeseRecipe: [{"ingredient":"Monterey Jack","lbs":5},{"ingredient":"Old Vienna Red Hot Riplet Seasoning","lbs":0.01}],
    app3CheeseRecipeName: "Red Hot Cheese Mix"
  } },
  { brand: "Four Hands", flavor: "CHICKEN BACON CLUB", values: {
    sauceOzPerPizza: 3,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 2.5,
    app2Type: "Club Mix",
    app2OzPerPizza: 1.85,
    app2CheeseRecipe: [{"ingredient":"FR Diced Tomatoes","lbs":1},{"ingredient":"Bacon","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}],
    app2CheeseRecipeName: "Club Mix",
    app3Type: "Chicken Bacon Club Cheese Mix",
    app3OzPerPizza: 4,
    app3CheeseRecipe: [{"ingredient":"Skim Mozz","lbs":3},{"ingredient":"Yellow Cheddar","lbs":1}],
    app3CheeseRecipeName: "Chicken Bacon Club Cheese Mix"
  } },
  { brand: "Four Hands", flavor: "SUGARFIRE BBQ CHICKEN", values: {
    sauceOzPerPizza: 3,
    app1Type: "Four Hands Surgarfire Chicken Mix",
    app1OzPerPizza: 2.52,
    app1CheeseRecipe: [{"ingredient":"Chicken","lbs":2.43},{"ingredient":"Liquid Smoke","lbs":0.09}],
    app1CheeseRecipeName: "Four Hands Surgarfire Chicken Mix",
    app2Type: "Red Onion, Diced",
    app2OzPerPizza: 0.73,
    app3Type: "Four Hands BBQ Chicken Cheese Mix",
    app3OzPerPizza: 4.05,
    app3CheeseRecipe: [{"ingredient":"Monterey Jack","lbs":3},{"ingredient":"Yellow Cheddar Cheese","lbs":1},{"ingredient":"Cilantro","lbs":0.05}],
    app3CheeseRecipeName: "Four Hands BBQ Chicken Cheese Mix"
  } },
  { brand: "Four Hands", flavor: "SEVEN CHEESE", values: {
    sauceOzPerPizza: 4,
    app1Type: "Four Hands 7Cheese Mix",
    app1OzPerPizza: 3,
    app1CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":1.85},{"ingredient":"White Cheddar","lbs":0.5},{"ingredient":"Provolone","lbs":0.25},{"ingredient":"Fontina","lbs":0.25},{"ingredient":"Three Cheese Blend","lbs":0.15}],
    app1CheeseRecipeName: "Four Hands 7Cheese Mix",
    app2Type: "Four Hands 7Cheese Mix",
    app2OzPerPizza: 3,
    app2CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":1.85},{"ingredient":"White Cheddar","lbs":0.5},{"ingredient":"Provolone","lbs":0.25},{"ingredient":"Fontina","lbs":0.25},{"ingredient":"Three Cheese Blend","lbs":0.15}],
    app2CheeseRecipeName: "Four Hands 7Cheese Mix"
  } },
  { brand: "Four Hands", flavor: "MISSION TACO MEXICAN", values: {
    sauceOzPerPizza: 3.5,
    pep1Sticks: 11,
    pep1OzPerPizza: 1.75,
    pep1Type: "Chorizo Stick",
    app1Type: "Pizella Cheese",
    app1OzPerPizza: 2.25,
    app2Type: "Four Hands Mission Taco Mexican Mix",
    app2OzPerPizza: 2.75,
    app2CheeseRecipe: [{"ingredient":"White Fajita Mix","lbs":2.45},{"ingredient":"Jalapenos","lbs":0.3}],
    app2CheeseRecipeName: "Four Hands Mission Taco Mexican Mix",
    app3Type: "Pizella Cheese",
    app3OzPerPizza: 2
  } },
  { brand: "Four Hands", flavor: "MICHAEL'S GYRO", values: {
    sauceOzPerPizza: 5,
    app1Type: "Gyro Meat Mix",
    app1OzPerPizza: 2.752,
    app1CheeseRecipe: [{"ingredient":"Gyro Meat","lbs":2.75},{"ingredient":"Gyro Spice Blend","lbs":0.002}],
    app1CheeseRecipeName: "Gyro Meat Mix",
    app2Type: "Gyro Veg Mix",
    app2OzPerPizza: 2.25,
    app2CheeseRecipe: [{"ingredient":"Tomatoes","lbs":1.25},{"ingredient":"FR Red Onion Strips","lbs":1}],
    app2CheeseRecipeName: "Gyro Veg Mix",
    app3Type: "Gyro Cheese Blend",
    app3OzPerPizza: 3.25,
    app3CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":3},{"ingredient":"Feta","lbs":0.25}],
    app3CheeseRecipeName: "Gyro Cheese Blend"
  } },
  { brand: "Four Hands", flavor: "BACON CHEESEBURGER", values: {
    sauceOzPerPizza: 3,
    app1Type: "Hamburger",
    app1OzPerPizza: 3,
    app2Type: "Cheeseburger Cheese Mix",
    app2OzPerPizza: 3,
    app2CheeseRecipe: [{"ingredient":"Whole Mozz","lbs":1.5},{"ingredient":"Yellow Cheddar","lbs":1.5}],
    app2CheeseRecipeName: "Cheeseburger Cheese Mix",
    app3Type: "Bacon Cheeseburger Mix",
    app3OzPerPizza: 1.5,
    app3CheeseRecipe: [{"ingredient":"Tomatoes","lbs":0.5},{"ingredient":"Bacon","lbs":0.5},{"ingredient":"FR White Onion Strips","lbs":0.5}],
    app3CheeseRecipeName: "Bacon Cheeseburger Mix",
    app4Type: "Cheeseburger Cheese Mix",
    app4OzPerPizza: 2,
    app4CheeseRecipe: [{"ingredient":"Whole Mozz","lbs":1},{"ingredient":"Yellow Cheddar","lbs":1}],
    app4CheeseRecipeName: "Cheeseburger Cheese Mix"
  } },
  { brand: "Four Hands", flavor: "CHICKEN TIKKA MASALA", values: {
    sauceOzPerPizza: 3.75,
    app1Type: "Masala Chicken Mix",
    app1OzPerPizza: 2.25,
    app1CheeseRecipe: [{"ingredient":"Chicken","lbs":2},{"ingredient":"Masala Sauce","lbs":0.25}],
    app1CheeseRecipeName: "Masala Chicken Mix",
    app2Type: "White Fajita Mix",
    app2OzPerPizza: 3.5,
    app2CheeseRecipe: [{"ingredient":"Blanched Red Pepper Strips","lbs":0.875},{"ingredient":"Blanched Green Pepper Strips","lbs":0.875},{"ingredient":"Blanched Yellow Pepper Strips","lbs":0.875},{"ingredient":"Blanched White Onion Strips","lbs":0.875}],
    app2CheeseRecipeName: "White Fajita Mix",
    app3Type: "Whole Milk Mozzarella Cheese",
    app3OzPerPizza: 4
  } },
  { brand: "Hannaford", flavor: "FIVE CHEESE", values: {
    sauceOzPerPizza: 3.5,
    app1Type: "Lowe's/Hannaford 5Cheese Mix",
    app1OzPerPizza: 2.5,
    app1CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":1.965},{"ingredient":"White Cheddar","lbs":0.49},{"ingredient":"Cheese Spice Blend","lbs":5}],
    app1CheeseRecipeName: "Lowe's/Hannaford 5Cheese Mix",
    app2Type: "Lowe's/Hannaford 5Cheese Mix",
    app2OzPerPizza: 2.5,
    app2CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":1.965},{"ingredient":"White Cheddar","lbs":0.49},{"ingredient":"Cheese Spice Blend","lbs":5}],
    app2CheeseRecipeName: "Lowe's/Hannaford 5Cheese Mix"
  } },
  { brand: "Hannaford", flavor: "BBQ CHICKEN", values: {
    sauceOzPerPizza: 2.25,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 2,
    app2Type: "Red Onion Diced",
    app2OzPerPizza: 0.5,
    app3Type: "BBQ Chicken Cheese Mix",
    app3OzPerPizza: 3.1,
    app3CheeseRecipe: [{"ingredient":"Monterey Jack","lbs":3},{"ingredient":"Cilantro","lbs":0.1}],
    app3CheeseRecipeName: "BBQ Chicken Cheese Mix"
  } },
  { brand: "Hannaford", flavor: "4 MEAT", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 9,
    pep1OzPerPizza: 0.8,
    pep1Type: "Pepperoni Stick",
    app1Type: "Hannaford 4Meat Mix",
    app1OzPerPizza: 2,
    app1CheeseRecipe: [{"ingredient":"Natural Italian Sausage","lbs":1.5},{"ingredient":"Natural Hamburger","lbs":0.5}],
    app1CheeseRecipeName: "Hannaford 4Meat Mix",
    app2Type: "Mozzarella Part Skim",
    app2OzPerPizza: 1.25,
    app3Type: "Bacon",
    app3OzPerPizza: 0.5,
    app4Type: "Mozzarella Part Skim",
    app4OzPerPizza: 2
  } },
  { brand: "Hannaford", flavor: "FOUR CHEESE WITH SWEET & SPICY\r\nCHILI SAUCE", values: {
    sauceOzPerPizza: 4,
    app1Type: "Hannaford's Spicy 4Cheese Mix",
    app1OzPerPizza: 2.5,
    app1CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":3},{"ingredient":"White Cheddar","lbs":1},{"ingredient":"Provolone","lbs":1},{"ingredient":"Grated Parmesan","lbs":0.25}],
    app1CheeseRecipeName: "Hannaford's Spicy 4Cheese Mix",
    app2Type: "Hannaford's Spicy 4Cheese Mix",
    app2OzPerPizza: 2.75,
    app2CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":3},{"ingredient":"White Cheddar","lbs":1},{"ingredient":"Provolone","lbs":1},{"ingredient":"Grated Parmesan","lbs":0.25}],
    app2CheeseRecipeName: "Hannaford's Spicy 4Cheese Mix"
  } },
  { brand: "Hannaford", flavor: "SPINACH GOAT CHEESE", values: {
    sauceOzPerPizza: 2.5,
    app1Type: "Tomatoes",
    app1OzPerPizza: 1,
    app2Type: "Hannaford Spinach Goat Cheese Mix",
    app2OzPerPizza: 4.1,
    app2CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":2.4},{"ingredient":"Spinach","lbs":0.6},{"ingredient":"Goat","lbs":1},{"ingredient":"Grated Parmesan","lbs":0.1}],
    app2CheeseRecipeName: "Hannaford Spinach Goat Cheese Mix"
  } },
  { brand: "Hannaford", flavor: "CHICKEN BACON CLUB", values: {
    sauceOzPerPizza: 2.5,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 2.5,
    app2Type: "Hannaford Club Mix",
    app2OzPerPizza: 0.85,
    app2CheeseRecipe: [{"ingredient":"Bacon","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}],
    app2CheeseRecipeName: "Hannaford Club Mix",
    app3Type: "Hannaford Club Cheese Mix",
    app3OzPerPizza: 4,
    app3CheeseRecipe: [{"ingredient":"Yellow Cheddar","lbs":2},{"ingredient":"Skim Mozz","lbs":2}],
    app3CheeseRecipeName: "Hannaford Club Cheese Mix"
  } },
  { brand: "Hannaford", flavor: "CHICKEN TIKKA MASALA", values: {
    sauceOzPerPizza: 3.5,
    app1Type: "Masala Chicken Mix",
    app1OzPerPizza: 2.07,
    app1CheeseRecipe: [{"ingredient":"Chicken","lbs":2},{"ingredient":"Masala Sauce","lbs":0.07}],
    app1CheeseRecipeName: "Masala Chicken Mix",
    app2Type: "White Fajita Mix",
    app2OzPerPizza: 1.5,
    app2CheeseRecipe: [{"ingredient":"Red Pepper Strips Blanched","lbs":0.375},{"ingredient":"Green Pepper Strips Blanched","lbs":0.375},{"ingredient":"Yellow Pepper Strips Blanched","lbs":0.375},{"ingredient":"White Onion Strips Blanched","lbs":0.375}],
    app2CheeseRecipeName: "White Fajita Mix",
    app3Type: "Whole Milk Mozzarella",
    app3OzPerPizza: 4
  } },
  { brand: "Lowe's", flavor: "FIVE CHEESE", values: {
    sauceOzPerPizza: 1.3,
    app1Type: "Lowe's/Hannaford 5Cheese Mix",
    app1OzPerPizza: 2,
    app1CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":1.57},{"ingredient":"White Cheddar","lbs":0.4},{"ingredient":"Three Cheese Blend &","lbs":0.03},{"ingredient":"Cheese Spice Blend","lbs":0.004}],
    app1CheeseRecipeName: "Lowe's/Hannaford 5Cheese Mix"
  } },
  { brand: "Lowe's", flavor: "MEAT LOVERS", values: {
    sauceOzPerPizza: 1.3,
    pep1Sticks: 4,
    pep1OzPerPizza: 0.2,
    pep1Type: "Pepperoni Stick - NATURAL",
    app1Type: "Natural Italian Sausage",
    app1OzPerPizza: 0.75,
    app2Type: "Mozzarella Part Skim",
    app2OzPerPizza: 0.8,
    app3Type: "Natural Bacon",
    app3OzPerPizza: 0.1,
    app4Type: "Mozzarella Part Skim",
    app4OzPerPizza: 0.8
  } },
  { brand: "Lowe's", flavor: "PEPPERONI", values: {
    sauceOzPerPizza: 1.3,
    pep1Sticks: 6,
    pep1OzPerPizza: 0.5,
    pep1Type: "Pepperoni Stick - NATURAL",
    app1Type: "Lowe's Pepperoni Cheese Mix",
    app1OzPerPizza: 0.7,
    app1CheeseRecipe: [{"ingredient":"P/S Mozz","lbs":0.44},{"ingredient":"Provolone","lbs":0.26}],
    app1CheeseRecipeName: "Lowe's Pepperoni Cheese Mix",
    app2Type: "Lowe's Pepperoni/Romano Cheese Mix",
    app2OzPerPizza: 0.8,
    app2CheeseRecipe: [{"ingredient":"P/S Mozz","lbs":0.44},{"ingredient":"Provolone","lbs":0.26},{"ingredient":"SHEEP Romano","lbs":0.1}],
    app2CheeseRecipeName: "Lowe's Pepperoni/Romano Cheese Mix"
  } },
  { brand: "Lowe's", flavor: "SUPREME", values: {
    sauceOzPerPizza: 1.3,
    pep1Sticks: 4,
    pep1OzPerPizza: 0.2,
    pep1Type: "Pepperoni Stick - NATURAL",
    app1Type: "Natural Italian Sausage",
    app1OzPerPizza: 0.75,
    app2Type: "Mozzarella Part Skim",
    app2OzPerPizza: 0.7,
    app3Type: "Diced Red Fajita Mix",
    app3OzPerPizza: 0.5,
    app4Type: "Mozzarella Part Skim",
    app4OzPerPizza: 0.7
  } },
  { brand: "Lowe's", flavor: "BBQ CHICKEN", values: {
    sauceOzPerPizza: 1.3,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 1,
    app2Type: "Red Onion Diced",
    app2OzPerPizza: 0.25,
    app3Type: "BBQ Chicken Cheese Mix",
    app3OzPerPizza: 1.29,
    app3CheeseRecipe: [{"ingredient":"Monterey Jack","lbs":1.25},{"ingredient":"Cilantro","lbs":0.04}],
    app3CheeseRecipeName: "BBQ Chicken Cheese Mix"
  } },
  { brand: "Lowe's", flavor: "WHITE SPINACH", values: {
    sauceOzPerPizza: 1,
    app1Type: "Lowe's Spinach Cheese Mix",
    app1OzPerPizza: 2.09,
    app1CheeseRecipe: [{"ingredient":"Part Skim Mozzarella","lbs":1.25},{"ingredient":"Fresh Spinach","lbs":0.8},{"ingredient":"Nutmeg","lbs":0.04}],
    app1CheeseRecipeName: "Lowe's Spinach Cheese Mix"
  } },
  { brand: "Morning Melts", flavor: "AMERICANO", values: {
    sauceOzPerPizza: 1.2,
    app1Type: "Scrambled Egg",
    app1OzPerPizza: 0.6,
    app2Type: "Spicy Breakfast Sausage",
    app2OzPerPizza: 0.6,
    app3Type: "Diced Ham",
    app3OzPerPizza: 0.4,
    app4Type: "Lucia's Americano Cheese Mix",
    app4OzPerPizza: 1,
    app4CheeseRecipe: [{"ingredient":"Skim Mozzarella","lbs":0.5},{"ingredient":"Yellow Cheddar","lbs":0.5}],
    app4CheeseRecipeName: "Lucia's Americano Cheese Mix"
  } },
  { brand: "Morning Melts", flavor: "ITALIANO", values: {
    sauceOzPerPizza: 1.2,
    app1Type: "Scrambled Egg",
    app1OzPerPizza: 0.6,
    app2Type: "Diced Blanched Red Pepper",
    app2OzPerPizza: 0.35,
    app3Type: "Vita Lucia's Italiano Cheese Mix",
    app3OzPerPizza: 1.2,
    app3CheeseRecipe: [{"ingredient":"Monterey Jack","lbs":1},{"ingredient":"Fresh Spinach","lbs":0.2}],
    app3CheeseRecipeName: "Vita Lucia's Italiano Cheese Mix"
  } },
  { brand: "Morning Melts", flavor: "MEXICANO", values: {
    sauceOzPerPizza: 1.5,
    app1Type: "Scrambled Egg",
    app1OzPerPizza: 0.6,
    app2Type: "Chorizo",
    app2OzPerPizza: 0.5,
    app3Type: "Lucia's Mexicano Cheese Mix",
    app3OzPerPizza: 1.01,
    app3CheeseRecipe: [{"ingredient":"Skim Mozzarella","lbs":0.5},{"ingredient":"Yellow Cheddar","lbs":0.5},{"ingredient":"IQF Cilantro","lbs":0.01}],
    app3CheeseRecipeName: "Lucia's Mexicano Cheese Mix"
  } },
  { brand: "Morning Melts", flavor: "PARISIAN", values: {
    sauceOzPerPizza: 1,
    app1Type: "Scrambled Egg",
    app1OzPerPizza: 0.6,
    app2Type: "Lucia's Parisian Meat Mix",
    app2OzPerPizza: 0.4,
    app2CheeseRecipe: [{"ingredient":"Diced Turkey","lbs":0.2},{"ingredient":"Diced Ham","lbs":0.2}],
    app2CheeseRecipeName: "Lucia's Parisian Meat Mix",
    app3Type: "Swiss Cheese",
    app3OzPerPizza: 0.75
  } },
  { brand: "Pinsa", flavor: "CHICKEN TIKKA MASALA", values: {
    sauceOzPerPizza: 2.5,
    app1Type: "Masala Chicken Mix",
    app1OzPerPizza: 2,
    app1CheeseRecipe: [{"ingredient":"Diced Chicken","lbs":1.93},{"ingredient":"Masala Sauce","lbs":0.07}],
    app1CheeseRecipeName: "Masala Chicken Mix",
    app2Type: "White Fajita Mix",
    app2OzPerPizza: 2.1,
    app2CheeseRecipe: [{"ingredient":"Blanched Red Pepper Strips","lbs":0.525},{"ingredient":"Blanched Green Pepper Strips","lbs":0.525},{"ingredient":"Blanched Yellow Pepper Strips","lbs":0.525},{"ingredient":"Blanched White Onion Strips","lbs":0.525}],
    app2CheeseRecipeName: "White Fajita Mix",
    app3Type: "Whole Mozzarella",
    app3OzPerPizza: 3.5
  } },
  { brand: "Pinsa", flavor: "MARGHERITA", values: {
    sauceOzPerPizza: 2,
    pep1Sticks: 0,
    pep1OzPerPizza: 0,
    pep1Type: "Mozzarella Stick",
    app1Type: "Pinsa Margherita Cheese Mix",
    app1OzPerPizza: 2.8,
    app1CheeseRecipe: [{"ingredient":"Whole Mozzarella-Extra Large Cut","lbs":2.5},{"ingredient":"Goat Cheese","lbs":0.25},{"ingredient":"IQF Basil","lbs":0.05}],
    app1CheeseRecipeName: "Pinsa Margherita Cheese Mix",
    app2Type: "Tomatoes",
    app2OzPerPizza: 2
  } },
  { brand: "Pinsa", flavor: "PEPPERONI", values: {
    sauceOzPerPizza: 3.5,
    pep1Sticks: 18,
    pep1OzPerPizza: 1.5,
    pep1Type: "Pepperoni Stick",
    app1Type: "Lucia's Pinsa Pepperoni Cheese Mix",
    app1OzPerPizza: 2.5,
    app1CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":1.97},{"ingredient":"Provolone","lbs":0.53}],
    app1CheeseRecipeName: "Lucia's Pinsa Pepperoni Cheese Mix",
    app2Type: "Lucia's Pinsa Pepperoni/Romano Cheese Mix",
    app2OzPerPizza: 1.5,
    app2CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":1.03},{"ingredient":"Provolone","lbs":0.27},{"ingredient":"Cow's Romano","lbs":0.2}],
    app2CheeseRecipeName: "Lucia's Pinsa Pepperoni/Romano Cheese Mix"
  } },
  { brand: "Pinsa", flavor: "PESTO SPINACH", values: {
    sauceOzPerPizza: 2.5,
    app1Type: "Whole Mozzarella",
    app1OzPerPizza: 1.75,
    app2Type: "IQF Mushrooms",
    app2OzPerPizza: 1.5,
    app3Type: "Pinsa Pesto Cheese Mix",
    app3OzPerPizza: 2.25,
    app3CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":1},{"ingredient":"Spinach","lbs":1},{"ingredient":"Parmesan","lbs":0.25}],
    app3CheeseRecipeName: "Pinsa Pesto Cheese Mix"
  } },
  { brand: "Craft", flavor: "CLUB", values: {
    sauceOzPerPizza: 3,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 2.5,
    app2Type: "4Hands Club Mix",
    app2OzPerPizza: 1.85,
    app2CheeseRecipe: [{"ingredient":"Diced Tomatoes","lbs":1},{"ingredient":"Bacon","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}],
    app2CheeseRecipeName: "4Hands Club Mix",
    app3Type: "Lucia's Club Cheese Mix",
    app3OzPerPizza: 4.5,
    app3CheeseRecipe: [{"ingredient":"Skim Mozzarella","lbs":3},{"ingredient":"Yellow Cheddar","lbs":1.5}],
    app3CheeseRecipeName: "Lucia's Club Cheese Mix"
  } },
  { brand: "Craft", flavor: "RED HOT CHICKEN", values: {
    sauceOzPerPizza: 3,
    app1Type: "4hands Red Hot Chicken Mix",
    app1OzPerPizza: 2.5,
    app1CheeseRecipe: [{"ingredient":"Diced Chicken","lbs":2.43},{"ingredient":"Vienna Red Hot Sauce","lbs":0.07}],
    app1CheeseRecipeName: "4hands Red Hot Chicken Mix",
    app2Type: "4Hands Red Hot Mix",
    app2OzPerPizza: 0.75,
    app2CheeseRecipe: [{"ingredient":"Bacon","lbs":0.5},{"ingredient":"Jalapenos","lbs":0.25}],
    app2CheeseRecipeName: "4Hands Red Hot Mix",
    app3Type: "Red Hot Cheese Mix Monterey Jack 5.0, Riplet Seasoning 0.01",
    app3OzPerPizza: 5.01
  } },
  { brand: "Craft", flavor: "ALFREDO CHICKEN & SPINACH", values: {
    sauceOzPerPizza: 3.5,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 3,
    app2Type: "Lucia's Spinach Cheese Mix",
    app2OzPerPizza: 5,
    app2CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":3.9},{"ingredient":"Fresh Spinach","lbs":0.98},{"ingredient":"Grated Parmesan","lbs":0.12}],
    app2CheeseRecipeName: "Lucia's Spinach Cheese Mix"
  } },
  { brand: "Craft", flavor: "BACON CHEESEBURGER", values: {
    sauceOzPerPizza: 3,
    app1Type: "Beef Topping",
    app1OzPerPizza: 2.75,
    app2Type: "Craft Cheeseburger Mix",
    app2OzPerPizza: 1.75,
    app2CheeseRecipe: [{"ingredient":"Diced Tomatoes","lbs":1.25},{"ingredient":"Bacon","lbs":0.5}],
    app2CheeseRecipeName: "Craft Cheeseburger Mix",
    app3Type: "Cheeseburger Cheese Mix",
    app3OzPerPizza: 5,
    app3CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":2.5},{"ingredient":"Yellow Cheddar","lbs":2.5}],
    app3CheeseRecipeName: "Cheeseburger Cheese Mix"
  } },
  { brand: "Craft", flavor: "CARIBBEAN", values: {
    sauceOzPerPizza: 4.25,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 3,
    app2Type: "Pineapple",
    app2OzPerPizza: 0.75,
    app3Type: "Carribean Mix",
    app3OzPerPizza: 1.5,
    app3CheeseRecipe: [{"ingredient":"Red Onion Strips","lbs":0.7},{"ingredient":"FR Green Pepper Strips","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2}],
    app3CheeseRecipeName: "Carribean Mix",
    app4Type: "Lucia's Craft Caribbean Cheese Mix",
    app4OzPerPizza: 4.65,
    app4CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":2.25},{"ingredient":"Provolone","lbs":2.25},{"ingredient":"Cilantro","lbs":0.15}],
    app4CheeseRecipeName: "Lucia's Craft Caribbean Cheese Mix"
  } },
  { brand: "Craft", flavor: "BRAT", values: {
    sauceOzPerPizza: 3.5,
    pep1Sticks: 18,
    pep1OzPerPizza: 3,
    pep1Type: "Bratwurst Sticks",
    app1Type: "Lucia's Craft Cheese Mix",
    app1OzPerPizza: 3,
    app1CheeseRecipe: [{"ingredient":"Whole Mozz","lbs":1.5},{"ingredient":"Provolone","lbs":1.5}],
    app1CheeseRecipeName: "Lucia's Craft Cheese Mix",
    app2Type: "Bratwurst Mix",
    app2OzPerPizza: 2.05,
    app2CheeseRecipe: [{"ingredient":"Sauerkraut","lbs":1.3},{"ingredient":"FR Yellow Onion Strips","lbs":0.75}],
    app2CheeseRecipeName: "Bratwurst Mix",
    app3Type: "Lucia's Craft Cheese Mix",
    app3OzPerPizza: 2,
    app3CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":1},{"ingredient":"Provolone","lbs":1}],
    app3CheeseRecipeName: "Lucia's Craft Cheese Mix"
  } },
  { brand: "Craft", flavor: "SOUTH OF THE BORDER", values: {
    sauceOzPerPizza: 2.5,
    app1Type: "Chorizo",
    app1OzPerPizza: 2,
    app2Type: "Hannaford South of Border Mix",
    app2OzPerPizza: 3.36,
    app2CheeseRecipe: [{"ingredient":"IQF Black Beans","lbs":0.74},{"ingredient":"Diced Tomatoes","lbs":0.71},{"ingredient":"FR Red Onion Strips","lbs":0.71},{"ingredient":"FR Corn","lbs":0.63},{"ingredient":"Yellow Pepper Strips","lbs":0.46},{"ingredient":"Cilantro","lbs":0.11}],
    app2CheeseRecipeName: "Hannaford South of Border Mix",
    app3Type: "Monterey Jack Cheese",
    app3OzPerPizza: 4
  } },
  { brand: "Craft", flavor: "CHICKEN TIKKA MASALA", values: {
    sauceOzPerPizza: 3.5,
    app1Type: "Masala Chicken Mix",
    app1OzPerPizza: 3,
    app1CheeseRecipe: [{"ingredient":"Diced Chicken","lbs":2.93},{"ingredient":"Masala Sauce","lbs":0.07}],
    app1CheeseRecipeName: "Masala Chicken Mix",
    app2Type: "White Fajita Mix",
    app2OzPerPizza: 1.5,
    app2CheeseRecipe: [{"ingredient":"Red Pepper Strips","lbs":0.37},{"ingredient":"Green Pepper Strips","lbs":0.37},{"ingredient":"Yellow Pepper Strips","lbs":0.37},{"ingredient":"White Onion Strips","lbs":0.37}],
    app2CheeseRecipeName: "White Fajita Mix",
    app3Type: "Whole Milk Mozzarella",
    app3OzPerPizza: 5
  } },
  { brand: "Lucia's", flavor: "6CHEESE", values: {
    sauceOzPerPizza: 4,
    app1Type: "Lucia's Six Cheese Mix",
    app1OzPerPizza: 4,
    app1CheeseRecipe: [{"ingredient":"Pizella","lbs":1.13},{"ingredient":"Yellow Cheddar","lbs":1.29},{"ingredient":"Whole Mozzarella","lbs":1.29},{"ingredient":"Fontina","lbs":0.23},{"ingredient":"Shredded Parmesan","lbs":0.06}],
    app1CheeseRecipeName: "Lucia's Six Cheese Mix",
    app2Type: "Lucia's Six Cheese Mix",
    app2OzPerPizza: 4,
    app2CheeseRecipe: [{"ingredient":"Pizella","lbs":1.13},{"ingredient":"Yellow Cheddar","lbs":1.29},{"ingredient":"Whole Mozzarella","lbs":1.29},{"ingredient":"Fontina","lbs":0.23},{"ingredient":"Shredded Parmesan","lbs":0.06}],
    app2CheeseRecipeName: "Lucia's Six Cheese Mix"
  } },
  { brand: "Lucia's", flavor: "PEPPERONI", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 19,
    pep1OzPerPizza: 1.5,
    pep1Type: "Pepperoni Stick",
    app1Type: "Lucia's Standard Cheese Mix",
    app1OzPerPizza: 2.5,
    app1CheeseRecipe: [{"ingredient":"Pizella","lbs":1.59},{"ingredient":"Whole Mozzarella","lbs":0.91}],
    app1CheeseRecipeName: "Lucia's Standard Cheese Mix",
    app2Type: "Lucia's Pepperoni Cheese Mix",
    app2OzPerPizza: 3,
    app2CheeseRecipe: [{"ingredient":"Pizella","lbs":1.62},{"ingredient":"Whole Mozzarella","lbs":0.92},{"ingredient":"Diced Pepperoni","lbs":0.46}],
    app2CheeseRecipeName: "Lucia's Pepperoni Cheese Mix"
  } },
  { brand: "Lucia's", flavor: "SAUSAGE", values: {
    sauceOzPerPizza: 4,
    app1Type: "Italian Sausage",
    app1OzPerPizza: 4,
    app2Type: "Lucia's Standard Cheese Mix",
    app2OzPerPizza: 5,
    app2CheeseRecipe: [{"ingredient":"Pizella","lbs":3.18},{"ingredient":"Whole Mozzarella","lbs":1.82}],
    app2CheeseRecipeName: "Lucia's Standard Cheese Mix"
  } },
  { brand: "Lucia's", flavor: "SSG & PEPP", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 19,
    pep1OzPerPizza: 1.1,
    pep1Type: "Pepperoni Stick",
    app1Type: "Italian Sausage",
    app1OzPerPizza: 2.5,
    app2Type: "Lucia's Standard Cheese Mix",
    app2OzPerPizza: 3,
    app2CheeseRecipe: [{"ingredient":"Pizella","lbs":1.91},{"ingredient":"Whole Mozzarella","lbs":1.09}],
    app2CheeseRecipeName: "Lucia's Standard Cheese Mix",
    app3Type: "Lucia's Standard Cheese Mix",
    app3OzPerPizza: 2,
    app3CheeseRecipe: [{"ingredient":"Pizella","lbs":1.27},{"ingredient":"Whole Mozzarella","lbs":0.73}],
    app3CheeseRecipeName: "Lucia's Standard Cheese Mix"
  } },
  { brand: "Lucia's", flavor: "MEAT LOVERS", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 16,
    pep1OzPerPizza: 1,
    pep1Type: "Pepperoni Stick",
    app1Type: "Italian Sausage",
    app1OzPerPizza: 2,
    app2Type: "Lucia's Standard Cheese Mix",
    app2OzPerPizza: 2.5,
    app2CheeseRecipe: [{"ingredient":"Pizella","lbs":1.59},{"ingredient":"Whole Mozzarella","lbs":0.91}],
    app2CheeseRecipeName: "Lucia's Standard Cheese Mix",
    app3Type: "Bacon",
    app3OzPerPizza: 0.7,
    app4Type: "Lucia's Standard Cheese Mix",
    app4OzPerPizza: 2,
    app4CheeseRecipe: [{"ingredient":"Pizella","lbs":1.27},{"ingredient":"Whole Mozzarella","lbs":0.73}],
    app4CheeseRecipeName: "Lucia's Standard Cheese Mix"
  } },
  { brand: "Lucia's", flavor: "CHEESE BURGER", values: {
    sauceOzPerPizza: 3.5,
    app1Type: "Natural Hamburger",
    app1OzPerPizza: 2.5,
    app2Type: "Onion FR Diced White/Yellow",
    app2OzPerPizza: 0.6,
    app3Type: "Cheese Burger Cheese Mix",
    app3OzPerPizza: 5,
    app3CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":2.5},{"ingredient":"Yellow Cheddar","lbs":2.5}],
    app3CheeseRecipeName: "Cheese Burger Cheese Mix"
  } },
  { brand: "Lucia's", flavor: "SUPREME", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 12,
    pep1OzPerPizza: 0.8,
    pep1Type: "Pepperoni Stick",
    app1Type: "Sausage",
    app1OzPerPizza: 1.7,
    app2Type: "Lucia's Standard Cheese Mix",
    app2OzPerPizza: 2.5,
    app2CheeseRecipe: [{"ingredient":"Pizella","lbs":1.59},{"ingredient":"Whole Mozzarella","lbs":0.91}],
    app2CheeseRecipeName: "Lucia's Standard Cheese Mix",
    app3Type: "Lucia's Red Fajita Mix",
    app3OzPerPizza: 3,
    app3CheeseRecipe: [{"ingredient":"Red Onion Strips","lbs":0.75},{"ingredient":"Green Pepper Strips","lbs":0.75},{"ingredient":"Red Pepper Strips","lbs":0.75},{"ingredient":"Yellow Pepper Strips","lbs":0.75}],
    app3CheeseRecipeName: "Lucia's Red Fajita Mix",
    app4Type: "Lucia's Standard Cheese Mix",
    app4OzPerPizza: 2,
    app4CheeseRecipe: [{"ingredient":"Pizella","lbs":1.27},{"ingredient":"Whole Mozzarella","lbs":0.73}],
    app4CheeseRecipeName: "Lucia's Standard Cheese Mix"
  } },
  { brand: "Lucia's", flavor: "BUFFALO CHICKEN", values: {
    sauceOzPerPizza: 3.25,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 2.5,
    app2Type: "Celery",
    app2OzPerPizza: 0.85,
    app3Type: "Monterey Jack Cheese",
    app3OzPerPizza: 5
  } },
  { brand: "Nob Hill", flavor: "SOUTH OF THE BORDER", values: {
    sauceOzPerPizza: 2.5,
    app1Type: "Chorizo",
    app1OzPerPizza: 2,
    app2Type: "Hannaford South of Border Mix",
    app2OzPerPizza: 3.36,
    app2CheeseRecipe: [{"ingredient":"IQF Black Beans","lbs":0.74},{"ingredient":"Diced Tomatoes","lbs":0.71},{"ingredient":"FR Red Onion Strips","lbs":0.71},{"ingredient":"FR Corn","lbs":0.63},{"ingredient":"Yellow Pepper Strips","lbs":0.46},{"ingredient":"Cilantro","lbs":0.11}],
    app2CheeseRecipeName: "Hannaford South of Border Mix",
    app3Type: "Monterey Jack Cheese",
    app3OzPerPizza: 4
  } },
  { brand: "Nob Hill", flavor: "BACON CHEESEBURGER", values: {
    sauceOzPerPizza: 3,
    app1Type: "Beef Topping",
    app1OzPerPizza: 2.75,
    app2Type: "Craft Cheeseburger Mix",
    app2OzPerPizza: 1.75,
    app2CheeseRecipe: [{"ingredient":"Diced Tomatoes","lbs":1.25},{"ingredient":"Bacon","lbs":0.5}],
    app2CheeseRecipeName: "Craft Cheeseburger Mix",
    app3Type: "Cheeseburger Cheese Mix",
    app3OzPerPizza: 5,
    app3CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":2.5},{"ingredient":"Yellow Cheddar","lbs":2.5}],
    app3CheeseRecipeName: "Cheeseburger Cheese Mix"
  } },
  { brand: "Nob Hill", flavor: "CLUB", values: {
    sauceOzPerPizza: 3,
    app1Type: "4Hands Club Mix",
    app1OzPerPizza: 1.85,
    app1CheeseRecipe: [{"ingredient":"Diced Tomatoes","lbs":1},{"ingredient":"Bacon","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}],
    app1CheeseRecipeName: "4Hands Club Mix",
    app2Type: "Diced Chicken",
    app2OzPerPizza: 2.5,
    app3Type: "Lucia's Club Cheese Mix",
    app3OzPerPizza: 4.5,
    app3CheeseRecipe: [{"ingredient":"Skim Mozzarella","lbs":3},{"ingredient":"Yellow Cheddar","lbs":1.5}],
    app3CheeseRecipeName: "Lucia's Club Cheese Mix"
  } },
  { brand: "Nob Hill", flavor: "RED HOT CHICKEN", values: {
    sauceOzPerPizza: 3,
    app1Type: "4Hands Red Hot Mix",
    app1OzPerPizza: 0.75,
    app1CheeseRecipe: [{"ingredient":"Bacon","lbs":0.5},{"ingredient":"Jalapenos","lbs":0.25}],
    app1CheeseRecipeName: "4Hands Red Hot Mix",
    app2Type: "4hands Red Hot Chicken Mix",
    app2OzPerPizza: 2.5,
    app2CheeseRecipe: [{"ingredient":"Diced Chicken","lbs":2.43},{"ingredient":"Vienna Red Hot Sauce","lbs":0.07}],
    app2CheeseRecipeName: "4hands Red Hot Chicken Mix",
    app3Type: "Red Hot Cheese Mix Monterey Jack 5.0, Riplet Seasoning 0.01",
    app3OzPerPizza: 5.01
  } },
  { brand: "Nob Hill", flavor: "CARIBBEAN", values: {
    sauceOzPerPizza: 4.25,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 3,
    app2Type: "Pineapple",
    app2OzPerPizza: 0.75,
    app3Type: "Carribean Mix",
    app3OzPerPizza: 1.5,
    app3CheeseRecipe: [{"ingredient":"FR Red Onion Strips","lbs":0.7},{"ingredient":"FR Green Pepper Strips","lbs":0.6},{"ingredient":"Jalapenos","lbs":0.2}],
    app3CheeseRecipeName: "Carribean Mix",
    app4Type: "Lucia's Craft Caribbean Cheese Mix",
    app4OzPerPizza: 4.65,
    app4CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":2.25},{"ingredient":"Provolone","lbs":2.25},{"ingredient":"Cilanto","lbs":0.15}],
    app4CheeseRecipeName: "Lucia's Craft Caribbean Cheese Mix"
  } },
  { brand: "Price Chopper", flavor: "BBQ CHICKEN", values: {
    sauceOzPerPizza: 2.25,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 2,
    app2Type: "Red Onion Diced",
    app2OzPerPizza: 0.5,
    app3Type: "BBQ Chicken Cheese Mix",
    app3OzPerPizza: 3.1,
    app3CheeseRecipe: [{"ingredient":"Monterey Jack","lbs":3},{"ingredient":"Cilantro","lbs":0.1}],
    app3CheeseRecipeName: "BBQ Chicken Cheese Mix"
  } },
  { brand: "Price Chopper", flavor: "BUFFALO CHICKEN", values: {
    sauceOzPerPizza: 3,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 2,
    app2Type: "Diced Celery",
    app2OzPerPizza: 0.7,
    app3Type: "Monterey Jack Cheese",
    app3OzPerPizza: 4
  } },
  { brand: "Price Chopper", flavor: "Chicken Bacon Club", values: {
    sauceOzPerPizza: 2.5,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 2.5,
    app2Type: "Hannaford Club Mix",
    app2OzPerPizza: 0.85,
    app2CheeseRecipe: [{"ingredient":"Bacon","lbs":0.7},{"ingredient":"Green Onion","lbs":0.15}],
    app2CheeseRecipeName: "Hannaford Club Mix",
    app3Type: "Hannaford Club Cheese Mix",
    app3OzPerPizza: 4,
    app3CheeseRecipe: [{"ingredient":"Yellow Cheddar","lbs":2},{"ingredient":"Skim Mozz","lbs":2}],
    app3CheeseRecipeName: "Hannaford Club Cheese Mix"
  } },
  { brand: "Price Chopper", flavor: "MEAT LOVERS", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 9,
    pep1OzPerPizza: 0.8,
    pep1Type: "Pepperoni Stick",
    app1Type: "Italian Sausage",
    app1OzPerPizza: 1.5,
    app2Type: "Mozzarella Part Skim",
    app2OzPerPizza: 1.25,
    app3Type: "Bacon",
    app3OzPerPizza: 1,
    app4Type: "Mozzarella Part Skim",
    app4OzPerPizza: 2
  } },
  { brand: "SMD", flavor: "FOUR CHEESE", values: {
    sauceOzPerPizza: 3.2,
    app1Type: "SMD Four Cheese Mix",
    app1OzPerPizza: 2.82,
    app1CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":2.1},{"ingredient":"Provolone","lbs":0.63},{"ingredient":"Yellow Cheddar","lbs":0.08},{"ingredient":"Cow's Romano","lbs":0.01}],
    app1CheeseRecipeName: "SMD Four Cheese Mix",
    app2Type: "SMD Four Cheese Mix",
    app2OzPerPizza: 2.82,
    app2CheeseRecipe: [{"ingredient":"Whole Mozzarella","lbs":2.1},{"ingredient":"Provolone","lbs":0.63},{"ingredient":"Yellow Cheddar","lbs":0.08},{"ingredient":"Cow's Romano","lbs":0.01}],
    app2CheeseRecipeName: "SMD Four Cheese Mix"
  } },
  { brand: "SMD", flavor: "PEPPERONI", values: {
    sauceOzPerPizza: 3,
    pep1Sticks: 19,
    pep1OzPerPizza: 1.4,
    pep1Type: "Pepperoni Stick",
    app1Type: "SMD Pep Cheese Mix",
    app1OzPerPizza: 2,
    app1CheeseRecipe: [{"ingredient":"Skim Mozzarella","lbs":1},{"ingredient":"Provolone","lbs":0.6},{"ingredient":"Diced Pepperoni","lbs":0.4}],
    app1CheeseRecipeName: "SMD Pep Cheese Mix",
    app2Type: "SMD Pep Cheese Mix",
    app2OzPerPizza: 3.25,
    app2CheeseRecipe: [{"ingredient":"Skim Mozzarella","lbs":1.5},{"ingredient":"Provolone","lbs":0.9},{"ingredient":"Diced Pepperoni","lbs":0.6},{"ingredient":"COW Romano Cheese","lbs":0.25}],
    app2CheeseRecipeName: "SMD Pep Cheese Mix"
  } },
  { brand: "SMD", flavor: "MEAT LOVERS", values: {
    sauceOzPerPizza: 3.2,
    pep1Sticks: 7,
    pep1OzPerPizza: 0.6,
    pep1Type: "Pepperoni Stick",
    app1Type: "Italian Sausage",
    app1OzPerPizza: 1.5,
    app2Type: "Whole Milk Mozzarella",
    app2OzPerPizza: 2.5,
    app3Type: "Bacon",
    app3OzPerPizza: 1,
    app4Type: "Whole Milk Mozzarella",
    app4OzPerPizza: 1.5
  } },
  { brand: "SMD", flavor: "SUPREME", values: {
    sauceOzPerPizza: 4,
    pep1Sticks: 7,
    pep1OzPerPizza: 0.6,
    pep1Type: "Pepperoni Stick",
    app1Type: "Italian Sausage",
    app1OzPerPizza: 1.75,
    app2Type: "HT Standard Cheese Mix",
    app2OzPerPizza: 2,
    app2CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":0.67},{"ingredient":"Fontina","lbs":0.67},{"ingredient":"Provolone","lbs":0.67}],
    app2CheeseRecipeName: "HT Standard Cheese Mix",
    app3Type: "Show Me Dough Supreme Mix",
    app3OzPerPizza: 1.9,
    app3CheeseRecipe: [{"ingredient":"White Fajita Blend","lbs":1.4},{"ingredient":"Black Olives","lbs":0.5}],
    app3CheeseRecipeName: "Show Me Dough Supreme Mix",
    app4Type: "HT Standard Cheese Mix",
    app4OzPerPizza: 1.5,
    app4CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":0.5},{"ingredient":"Fontina","lbs":0.5},{"ingredient":"Provolone","lbs":0.5}],
    app4CheeseRecipeName: "HT Standard Cheese Mix"
  } },
  { brand: "SMD", flavor: "BBQ CHICKEN", values: {
    sauceOzPerPizza: 3,
    app1Type: "Diced Chicken",
    app1OzPerPizza: 2,
    app2Type: "Red Onion Diced",
    app2OzPerPizza: 0.5,
    app3Type: "SMD BBQ Chicken Cheese Mix",
    app3OzPerPizza: 4,
    app3CheeseRecipe: [{"ingredient":"Whole Milk Mozzarella","lbs":3.5},{"ingredient":"Yellow Cheddar","lbs":0.5}],
    app3CheeseRecipeName: "SMD BBQ Chicken Cheese Mix"
  } },
  ];
  