const colors = {
  light: {
    text: "#f2f2f7",
    tint: "#ff6b35",
    background: "#0d0d0d",
    foreground: "#f2f2f7",
    card: "#1c1c1e",
    cardForeground: "#f2f2f7",
    primary: "#ff6b35",
    primaryForeground: "#ffffff",
    secondary: "#2c2c2e",
    secondaryForeground: "#f2f2f7",
    muted: "#2c2c2e",
    mutedForeground: "#8e8e93",
    accent: "#ff6b35",
    accentForeground: "#ffffff",
    destructive: "#ff453a",
    destructiveForeground: "#ffffff",
    border: "#38383a",
    input: "#2c2c2e",
    success: "#30d158",
    warning: "#ffd60a",
  },
  dark: {
    text: "#f2f2f7",
    tint: "#ff6b35",
    background: "#0d0d0d",
    foreground: "#f2f2f7",
    card: "#1c1c1e",
    cardForeground: "#f2f2f7",
    primary: "#ff6b35",
    primaryForeground: "#ffffff",
    secondary: "#2c2c2e",
    secondaryForeground: "#f2f2f7",
    muted: "#2c2c2e",
    mutedForeground: "#8e8e93",
    accent: "#ff6b35",
    accentForeground: "#ffffff",
    destructive: "#ff453a",
    destructiveForeground: "#ffffff",
    border: "#38383a",
    input: "#2c2c2e",
    success: "#30d158",
    warning: "#ffd60a",
  },
  radius: 12,
};

export default colors;
