/**
 * Bundle only reviewed, automatic reconciliation actions for the API. This
 * generator is intentionally file-only: no database or API access is needed.
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(process.cwd(), "..");
const REPORT = path.join(ROOT, "attached_assets/source-library/audits/source-library-reconciliation-2026-08-26.json");
const OUTPUT = path.join(ROOT, "artifacts/api-server/src/lib/sourceLibraryReconciliationPlan.generated.ts");
const sha = (value: string | Buffer) => crypto.createHash("sha256").update(value).digest("hex");
const stable = (value: unknown) => JSON.stringify(value);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);

function automaticProposals(report: Record<string, unknown>, action: string) {
  if (!Array.isArray(report.proposals)) throw new Error("Invalid reconciliation report proposals");
  return report.proposals
    .filter((proposal): proposal is Record<string, unknown> => isRecord(proposal) && proposal.classification === "automatic" && proposal.action === action)
    .sort((a, b) => stable(a.before).localeCompare(stable(b.before)));
}

export function sourceLibraryHealPlan(value: unknown) {
  if (!isRecord(value) || !isRecord(value.findings) || !Array.isArray(value.findings.allZeroStubs)) {
    throw new Error("Invalid reconciliation report");
  }
  const allZeroStubs = value.findings.allZeroStubs
    .filter((stub): stub is Record<string, unknown> => isRecord(stub) && typeof stub.canonicalId === "string" && typeof stub.canonicalName === "string")
    .map(({ table, id, name, canonicalId, canonicalName }) => ({ table, id, name, canonicalId, canonicalName }))
    .sort((a, b) => String(a.id).localeCompare(String(b.id)));
  if (allZeroStubs.length !== 3) throw new Error("Expected exactly three canonical all-zero stubs");
  return {
    replacements: automaticProposals(value, "replace-components-from-approved-source"),
    links: automaticProposals(value, "link-source-identity"),
    allZeroStubs,
  };
}

export function generatedSource(plan: ReturnType<typeof sourceLibraryHealPlan>): string {
  const json = stable(plan);
  // Node emits gzip streams with the mtime header zeroed; fixing level avoids
  // compressor-default drift while keeping the base64 reproducible.
  const gzipBase64 = gzipSync(Buffer.from(json), { level: 9 }).toString("base64");
  return `// Generated by scripts/src/generate-source-library-heal-plan.mts; DO NOT EDIT.\n` +
    `export const SOURCE_LIBRARY_RECONCILIATION_PLAN_GZIP_BASE64 = ${JSON.stringify(gzipBase64)};\n` +
    `export const SOURCE_LIBRARY_RECONCILIATION_PLAN_SHA256 = ${JSON.stringify(sha(json))};\n`;
}

function main() {
  const check = process.argv.includes("--check");
  const source = generatedSource(sourceLibraryHealPlan(JSON.parse(fs.readFileSync(REPORT, "utf8"))));
  if (check) {
    if (!fs.existsSync(OUTPUT) || fs.readFileSync(OUTPUT, "utf8") !== source) {
      throw new Error("Generated source-library reconciliation plan is stale; run pnpm --filter @workspace/scripts run audit:source-heal-plan");
    }
    console.log("Source-library reconciliation heal plan is current.");
    return;
  }
  fs.writeFileSync(OUTPUT, source);
  console.log(`Wrote ${path.relative(ROOT, OUTPUT)}`);
}
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) main();