import { Router, type IRouter } from "express";
import duplicateReviewsRouter from "../duplicateReviews";
import importAliasesRouter from "../importAliases";
import fillMissingValuesRouter from "../fillMissingValues";
import ingredientBatchWeightsRouter from "../ingredientBatchWeights";
import photoAliasesRouter from "../photoAliases";
import specImportAliasesRouter from "../specImportAliases";
import savedSpecSheetsRouter from "../savedSpecSheets";
import savedShippingGuidesRouter from "../savedShippingGuides";
import savedPremixSheetsRouter from "../savedPremixSheets";
import savedCheeseSheetsRouter from "../savedCheeseSheets";
import importHistoryRouter from "../importHistory";
import masterDataBootstrapRouter from "../masterDataBootstrap";
import mergeAliasesRouter from "../mergeAliases";
import deniedMergesRouter from "../deniedMerges";
import mergedAwayRouter from "../mergedAway";
import productionRulesRouter from "../productionRules";
import mixesRouter from "../mixes";
import ingredientsRouter from "../ingredients";
import cheeseRecipesRouter from "../cheeseRecipes";
import doughRecipesRouter from "../doughRecipes";
import sauceRecipesRouter from "../sauceRecipes";
import brandProfilesRouter from "../brandProfiles";
import cycleCountSchedulesRouter from "../cycleCountSchedules";
import runTemplatesRouter from "../runTemplates";
import dieTypesRouter from "../dieTypes";
import dieLineDefaultsRouter from "../dieLineDefaults";
import factoryDataRouter from "../factoryData";

/** Factory setup, recipe libraries, source imports, and merge/reconciliation data. */
const router: IRouter = Router();

router.use(duplicateReviewsRouter);
router.use(importAliasesRouter);
router.use(fillMissingValuesRouter);
router.use(ingredientBatchWeightsRouter);
router.use(photoAliasesRouter);
router.use(specImportAliasesRouter);
router.use(savedSpecSheetsRouter);
router.use(savedShippingGuidesRouter);
router.use(savedPremixSheetsRouter);
router.use(savedCheeseSheetsRouter);
router.use(importHistoryRouter);
router.use(masterDataBootstrapRouter);
router.use(mergeAliasesRouter);
router.use(deniedMergesRouter);
router.use(mergedAwayRouter);
router.use(productionRulesRouter);
router.use(mixesRouter);
router.use(ingredientsRouter);
router.use(cheeseRecipesRouter);
router.use(doughRecipesRouter);
router.use(sauceRecipesRouter);
router.use(brandProfilesRouter);
router.use(cycleCountSchedulesRouter);
router.use(runTemplatesRouter);
router.use(dieTypesRouter);
router.use(dieLineDefaultsRouter);
router.use(factoryDataRouter);

export default router;