// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/screen-improvements/DoughTabCurrent.tsx": () => import("../components/mockups/screen-improvements/DoughTabCurrent.tsx"),
  "./components/mockups/screen-improvements/DoughTabImproved.tsx": () => import("../components/mockups/screen-improvements/DoughTabImproved.tsx"),
  "./components/mockups/screen-improvements/FrontlineTabCurrent.tsx": () => import("../components/mockups/screen-improvements/FrontlineTabCurrent.tsx"),
  "./components/mockups/screen-improvements/FrontlineTabImproved.tsx": () => import("../components/mockups/screen-improvements/FrontlineTabImproved.tsx"),
  "./components/mockups/screen-improvements/LoginCurrent.tsx": () => import("../components/mockups/screen-improvements/LoginCurrent.tsx"),
  "./components/mockups/screen-improvements/LoginImproved.tsx": () => import("../components/mockups/screen-improvements/LoginImproved.tsx"),
  "./components/mockups/screen-improvements/PackTabCurrent.tsx": () => import("../components/mockups/screen-improvements/PackTabCurrent.tsx"),
  "./components/mockups/screen-improvements/PackTabImproved.tsx": () => import("../components/mockups/screen-improvements/PackTabImproved.tsx"),
  "./components/mockups/screen-improvements/RunTabCurrent.tsx": () => import("../components/mockups/screen-improvements/RunTabCurrent.tsx"),
  "./components/mockups/screen-improvements/RunTabImproved.tsx": () => import("../components/mockups/screen-improvements/RunTabImproved.tsx"),
  "./components/mockups/screen-improvements/SauceTabCurrent.tsx": () => import("../components/mockups/screen-improvements/SauceTabCurrent.tsx"),
  "./components/mockups/screen-improvements/SauceTabImproved.tsx": () => import("../components/mockups/screen-improvements/SauceTabImproved.tsx"),
  "./components/mockups/screen-improvements/WarehouseTabCurrent.tsx": () => import("../components/mockups/screen-improvements/WarehouseTabCurrent.tsx"),
  "./components/mockups/screen-improvements/WarehouseTabImproved.tsx": () => import("../components/mockups/screen-improvements/WarehouseTabImproved.tsx")
};
