// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ui-directions/ColorStatus.tsx": () => import("../components/mockups/ui-directions/ColorStatus.tsx"),
  "./components/mockups/ui-directions/Compact.tsx": () => import("../components/mockups/ui-directions/Compact.tsx"),
  "./components/mockups/ui-directions/Simplified.tsx": () => import("../components/mockups/ui-directions/Simplified.tsx")
};
